#!/bin/sh
set -e

truncate -s 0 ocr.txt

function ocr {
  name=`tesseract $1 stdout 2>/dev/null`
  name=`echo -n $name`
  name=`tr [[:upper:]] [[:lower:]] <<< "$name"`
  name=`sed s/0/o/g <<< "$name"`
  name=`sed 's/[^a-z]/ /g' <<< "$name"`
  name=`sed 's/\s\+/_/g' <<< "$name"`
  echo "$name"
}

function reencode {
  # transparent corners
  convert $1 -virtual-pixel transparent -channel A -blur 0x20 $2.gif
  # webp
  ffmpeg -y -i $2.gif -vf scale=600:-1 -preset drawing -compression_level 6 -qscale 50 $2.webp
  # jpg
  convert -background white -alpha remove -strip -interlace Plane -quality 80 -resize 300 $2.gif $2.jpg
}

# power cards
#for f in {base,branchclaw,promo}/{major,minor,spirit}-*.ppm; do
  #if [ ! -f $f ]; then
    #continue
  #fi
  #base="`dirname $f`/`basename $f .ppm`"

  ## ocr name
  #convert -crop 500x100+200+40 -level 65%,75% $f $base.pbm
  #name=`ocr "$base.pbm"`
  #echo $name
  #echo $base $name >> ocr.txt

  #reencode "$f" "$base"
#done

## fear cards
#for f in {base,branchclaw,promo}/fear-*.ppm; do
  #if [ ! -f $f ]; then
    #continue
  #fi
  #base="`dirname $f`/`basename $f .ppm`"

  ## ocr name
  #convert -crop 650x82+45+40 -level 65%,75% $f $base.pbm
  #name=`ocr "$base.pbm"`
  #echo $name
  #echo $base $name >> ocr.txt

  #reencode "$f" "$base"
#done
## "Panic" is not ocr'd correctly
#echo branchclaw/fear-012 panic >> ocr.txt

# event cards
for f in {base,branchclaw,promo}/event-*.ppm; do
  if [ ! -f $f ]; then
    continue
  fi
  base="`dirname $f`/`basename $f .ppm`"

  # ocr name
  convert -crop 530x82+130+40 -level 65%,75% $f $base.pbm
  name=`ocr "$base.pbm"`
  echo $name
  echo $base $name >> ocr.txt

  reencode "$f" "$base"
done
