#!/usr/bin/env bash
set -eou pipefail

for pdf in {base,branchclaw,jagged-earth,promo,promo2}/*.pdf; do
    echo extracting "$pdf"
    dir=$(dirname "$pdf")
    name=$(basename "$pdf" .pdf)
    name=${name:6}
    pdfimages "$pdf" "$dir/$name"
done
