// This file contains material owned by Greater Than Games, LLC.

/// <reference path="types.ts" />

namespace DB {
    const { Card, Unique, Speed, Ranges, Source, LandAny, Elements, TargetSpirit, TargetProperty, Land, CardType } = Types;

    export const CARDS = [
        // Spirit Cards
        new Card(Unique.LightngingsSwiftStrike, "Shatter Homesteads", 2, Speed.Slow, new Ranges(Source.SacredSite, 2), LandAny,
            [Elements.Fire, Elements.Air], "Rocky Hammer",
            "1 Fear. Destroy 1 Town."),
        new Card(Unique.LightngingsSwiftStrike, "Raging Storm", 3, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Fire, Elements.Air, Elements.Water], "Rocky Hammer",
            "1 Damage to each Invader."),
        new Card(Unique.LightngingsSwiftStrike, "Lighning's Boon", 1, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Fire, Elements.Air], "Rocky Hammer",
            "Target Spirit may use up to 2 Slow Powers as if they were Fast Powers this turn"),
        new Card(Unique.LightngingsSwiftStrike, "Harbingers of the Lightning", 0, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Fire, Elements.Air], "Rocky Hammer",
            "Push up to 2 Dahan. 1 Fear if you pushed any Dahan into a land with Town / City"),
        new Card(Unique.RiverSurgesInSunlight, "Flash Floods", 2, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Sun, Elements.Water], "Nolan Nasser",
            "1 Damage. If target land is Coastal, +1 Damage."),
        new Card(Unique.RiverSurgesInSunlight, "Wash Away", 1, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Water, Elements.Earth], "Nolan Nasser",
            "Push up to 3 Explorer / Town"),
        new Card(Unique.RiverSurgesInSunlight, "Boon of Vigor", 0, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Water, Elements.Plant], "Nolan Nasser",
            "If you target yourself, gain 1 Energy. If you target another Spirit, they gain 1 Energy per Power Card they played this turn."),
        new Card(Unique.RiverSurgesInSunlight, "River's Bounty", 0, Speed.Slow, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Sun, Elements.Water, Elements.Animal], "Nolan Nasser",
            "Gather up to 2 Dahan. If there are now at least 2 Dahan, add 1 Dahan and gain 1 Energy."),
        new Card(Unique.ShadowsFlickerLikeFlame, "Concealing Shadows", 0, Speed.Fast, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Moon, Elements.Air], "Nolan Nasser",
            "1 Fear. Dahan take no damage from Ravaging Invaders this turn."),
        new Card(Unique.ShadowsFlickerLikeFlame, "Favors Called Due", 1, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Moon, Elements.Air, Elements.Animal], "Nolan Nasser",
            "Gather up to 4 Dahan. If Invaders are present and Dahan now outnumber them, 3 Fear."),
        new Card(Unique.ShadowsFlickerLikeFlame, "Mantle of Dread", 1, Speed.Slow, null, TargetSpirit.Any,
            [Elements.Moon, Elements.Fire, Elements.Air], "Nolan Nasser",
            "2 Fear. Target Spirit may Push 1 Explorer and 1 Town from one of their lands."),
        new Card(Unique.ShadowsFlickerLikeFlame, "Crops Wither and Fade", 1, Speed.Slow, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Plant], "Nolan Nasser",
            "2 Fear. Replace 1 Town with 1 Explorer. -or- Replace 1 City with 1 Town."),
        new Card(Unique.VitalStrengthOfTheEarth, "Guard the Healing Land", 3, Speed.Fast, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Water, Elements.Earth, Elements.Plant], "Sydni Kruger",
            "Remove 1 Blight. Defend 4."),
        new Card(Unique.VitalStrengthOfTheEarth, "A Year of Perfect Stillness", 3, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Sun, Elements.Earth], "Sydni Kruger",
            "Invaders skipp all Actions in target land this turn."),
        new Card(Unique.VitalStrengthOfTheEarth, "Rituals of Destruction", 3, Speed.Slow, new Ranges(Source.SacredSite, 1), TargetProperty.Dahan,
            [Elements.Sun, Elements.Moon, Elements.Fire, Elements.Earth, Elements.Plant], "Sydni Kruger",
            "2 Damage. If target land has at least 3 Dahan, +3 Damage and 2 Fear."),
        new Card(Unique.VitalStrengthOfTheEarth, "Draw of the Fruitful Earth", 1, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Earth, Elements.Plant, Elements.Animal], "Sydni Kruger",
            "Gather up to 2 Explorer. Gather up to 2 Dahan."),
        new Card(Unique.Thunderspeaker, "Manifestation of Power and Glory", 3, Speed.Slow, new Ranges(Source.Presence, 0), TargetProperty.Dahan,
            [Elements.Sun, Elements.Fire, Elements.Air], "Loic Belliau",
            "1 Fear. Each Dahan deals damage equal to the number of your Presence in target land."),
        new Card(Unique.Thunderspeaker, "Words of Warning", 1, Speed.Fast, new Ranges(Source.Presence, 1), TargetProperty.Dahan,
            [Elements.Sun, Elements.Air, Elements.Animal], "Loic Belliau",
            "Defend 3. During Ravage, Dahan in target land deal damage simultaneously with Invaders."),
        new Card(Unique.Thunderspeaker, "Sudden Ambush", 2, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Fire, Elements.Air, Elements.Animal], "Loic Belliau",
            "You may Gather 1 Dahan. Each Dahan destroys 1 Explorer."),
        new Card(Unique.Thunderspeaker, "Voice of Thunder", 0, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Sun, Elements.Air], "Loic Belliau",
            "Push up to 4 Dahan. -or- If Invaders are Present, 2 Fear."),
        new Card(Unique.OceansHungryGrasp, "Call of the Deeps", 0, Speed.Fast, new Ranges(Source.Presence, 0), Land.Coastal,
            [Elements.Moon, Elements.Air, Elements.Water], "Joshua Wright",
            "Gather 1 Explorer. If target land is the Ocean, you may Gather another Explorer."),
        new Card(Unique.OceansHungryGrasp, "Grasping Tide", 1, Speed.Fast, new Ranges(Source.Presence, 1), Land.Coastal,
            [Elements.Moon, Elements.Water], "Joshua Wright",
            "2 Fear. Defend 4."),
        new Card(Unique.OceansHungryGrasp, "Swallow the Land-Dwellers", 0, Speed.Slow, new Ranges(Source.Presence, 0), Land.Coastal,
            [Elements.Water, Elements.Earth], "Joshua Wright",
            "Drown 1 Explorer, 1 Town, and 1 Dahan."),
        new Card(Unique.OceansHungryGrasp, "Tidal Boon", 1, Speed.Slow, null, TargetSpirit.Another,
            [Elements.Moon, Elements.Water, Elements.Earth], "Joshua Wright",
            "Target Spirit gains 2 Energy and may Push 1 Town and up to 2 Dahan from one of their lands. If Dahan are pushed to your ocean, you may move them to any Coastal land instead of Drowning them."),
        new Card(Unique.BringerOfDreamsAndNightmares, "Predatory Nightmares", 2, Speed.Slow, new Ranges(Source.SacredSite, 1), TargetProperty.Invaders,
            [Elements.Moon, Elements.Fire, Elements.Earth, Elements.Animal], "Shane Tyree",
            "2 Damage. Push up to 2 Dahan. (When your powers would destroy Invaders, instead they generate Fear and/or Push those Invaders.)"),
        new Card(Unique.BringerOfDreamsAndNightmares, "Dread Apparitions", 2, Speed.Fast, new Ranges(Source.Presence, 1), TargetProperty.Invaders,
            [Elements.Moon, Elements.Air], "Shane Tyree",
            "When Powers generate Fear in target land, Defend 1 per Fear. 1 Fear. (Fear from To Dream a Thousand Death counts. Fear from Destroying Town / City does not."),
        new Card(Unique.BringerOfDreamsAndNightmares, "Call on Midnight's Dreams", 0, Speed.Fast, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Moon, Elements.Animal], "Shane Tyree",
            "If target land has Dahan, gain a Major Power. If you Forget this Power, gain Energy equal to Dahan and you may play the Major Power immediately, paying its cost. -or- If Invaders are present, 2 Fear."),
        new Card(Unique.BringerOfDreamsAndNightmares, "Dreams of the Dahan", 0, Speed.Fast, new Ranges(Source.Presence, 2), LandAny,
            [Elements.Moon, Elements.Air], "Shane Tyree",
            "Gather up to 2 Dahan. -or- If target land has Town / City, 1 Fear for each Dahan, to a maximum of 3 Fear."),
        new Card(Unique.ASpreadOfRampantGreen, "Overgrow in a Night", 2, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Moon, Elements.Plant], "Jorge Ramos",
            "Add 1 Presence. -or- If target land has your Presence and Invaders, 3 Fear."),
        new Card(Unique.ASpreadOfRampantGreen, "Gift of Proliferation", 1, Speed.Fast, null, TargetSpirit.Another,
            [Elements.Moon, Elements.Plant], "Jorge Ramos",
            "Target Spirit adds 1 Presence up to 1 Range from their Presence."),
        new Card(Unique.ASpreadOfRampantGreen, "Fields Choked with Growth", 0, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Sun, Elements.Water, Elements.Plant], "Jorge Ramos",
            "Push 1 Town. -or- Push 3 Dahan"),
        new Card(Unique.ASpreadOfRampantGreen, "Stem the Flow of Fresh Water", 0, Speed.Slow, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Water, Elements.Plant], "Jorge Ramos",
            "1 Damage to 1 Town or 1 City. If target land is M/S, instead, 1 Damage to each Town / City."),

        // Colored Corners
        // green corner
        new Card(CardType.BasegameMinor, "Savage Mawbeasts", 0, Speed.Slow, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Fire, Elements.Animal], "Cari Corene",
            "If target land is J/W, 1 Fear and 1 Damage. -If you have- 3 Animal: 1 Damage."),
        new Card(CardType.BasegameMinor, "Voracious Growth", 1, Speed.Slow, new Ranges(Source.SacredSite, 1), [Land.Jungle, Land.Wetland],
            [Elements.Water, Elements.Plant], "Cari Corene",
            "2 Damage. -or- Remove 1 Blight."),
        new Card(CardType.BasegameMinor, "Rouse the Trees and Stones", 1, Speed.Slow, new Ranges(Source.SacredSite, 1), TargetProperty.NoBlight,
            [Elements.Fire, Elements.Earth, Elements.Plant], "Jorge Ramos",
            "2 Damage. Push 1 Explorer."),
        // blue corner
        new Card(CardType.BasegameMinor, "Encompassing Ward", 1, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Water, Elements.Earth], "Jorge Ramos",
            "Defend 2 in every land where target Spirit has Presence."),
        new Card(CardType.BasegameMinor, "Song of Sanctity", 1, Speed.Slow, new Ranges(Source.Presence, 1), [Land.Mountain, Land.Jungle],
            [Elements.Sun, Elements.Water, Elements.Plant], "Nolan Nasser",
            "If target land has 1 Explorer, Push all Explorer. Otherwise, remove 1 Blight."),
        new Card(CardType.BasegameMinor, "Uncanny Melting", 1, Speed.Slow, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Sun, Elements.Moon, Elements.Water], "Joshua Wright",
            "If Invaders are present, 1 Fear. If target land is S/W, remove 1 Blight"),
        // red corner
        new Card(CardType.BasegameMinor, "Shadows of the Burning Forest", 0, Speed.Slow, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Plant], "Nolan Nasser",
            "If Invaders are present, 2 Fear. If target land is M/J, Push 1 Explorer and 1 Town."),

        // Minors inside color cornered block
        new Card(CardType.BasegameMinor, "Steam Vents", 1, Speed.Fast, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Fire, Elements.Air, Elements.Water, Elements.Earth], "Joshua Wright",
            "Destroy 1 Explorer. -If you have- 3 Earth: You may instead destroy 1 Town."),
        new Card(CardType.BasegameMinor, "Veil the Night's Hunt", 1, Speed.Fast, new Ranges(Source.Presence, 2), TargetProperty.Dahan,
            [Elements.Moon, Elements.Air, Elements.Animal], "Loic Belliau",
            "Each Dahan deals 1 Damage to a different Invader. -or- Push up to 3 Dahan."),
        new Card(CardType.BasegameMinor, "Elemental Boon", 1, Speed.Fast, null, TargetSpirit.Any,
            [], "Moro Rogers",
            "Target Spirit gains 3 different Elements of their choice. If you target another Spirit, you also gain the chosen Elements."),

        // Second Badge
        // Minors
        new Card(CardType.BasegameMinor, "Devouring Ants", 1, Speed.Slow, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Sun, Elements.Earth, Elements.Animal], "Nolan Nasser",
            "1 Fear. 1 Damage. Destroy 1 Dahan. If target land is J/S, +1 Damage."),
        new Card(CardType.BasegameMinor, "Dark and Tangled Woods", 1, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Moon, Elements.Earth, Elements.Plant], "Nolan Nasser",
            "2 Fear. If target and is M/J, Defend 3."),
        new Card(CardType.BasegameMinor, "Sap the Strength of Multitudes", 0, Speed.Fast, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Water, Elements.Animal], "Loic Belliau",
            "Defend 5. -If you have- 1 Air: Increase this Power's Range by 1"),
        new Card(CardType.BasegameMinor, "Drift down into Slumber", 0, Speed.Fast, new Ranges(Source.Presence, 2), LandAny,
            [Elements.Air, Elements.Earth, Elements.Plant], "Lucas Durham",
            "Defend 1. If target land is J/S, instead, Defend 4."),
        new Card(CardType.BasegameMinor, "Land of Haunts and Embers", 0, Speed.Fast, new Ranges(Source.Presence, 2), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Air], "Jorge Ramos",
            "2 Fear. Push up to 2 Explorer / Town. If target land has Blight, +2 Fear. Push up to 2 more Explorer / Town. Add 1 Blight."),
        new Card(CardType.BasegameMinor, "Nature's Resilience", 1, Speed.Fast, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Earth, Elements.Plant, Elements.Animal], "Joshua Wright",
            "Defend 6. -If you have- 2 Water: You may instead remove 1 Blight."),
        new Card(CardType.BasegameMinor, "Visions of Fiery Doom", 1, Speed.Fast, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Moon, Elements.Fire], "Lucas Durham",
            "1 Fear. Push 1 Explorer / Town. -If you have- 2 Fire: +1 Fear."),
        new Card(CardType.BasegameMinor, "Pull Beneath the Hungry Earth", 1, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Moon, Elements.Water, Elements.Earth], "Nolan Nasser",
            "If target land has your Presence, 1 Fear and 1 Damage. If target land is S/W, 1 Damage."),
        new Card(CardType.BasegameMinor, "Call of the Dahan Ways", 1, Speed.Slow, new Ranges(Source.Presence, 1), TargetProperty.Dahan,
            [Elements.Moon, Elements.Water, Elements.Animal], "Loic Belliau",
            "Replace 1 Explorer with 1 Dahan. -If you have- 2 Moon: You may instead replace 1 Town with 1 Dahan."),
        new Card(CardType.BasegameMinor, "Call to Bloodshed", 1, Speed.Slow, new Ranges(Source.Presence, 1), TargetProperty.Dahan,
            [Elements.Sun, Elements.Fire, Elements.Animal], "Jorge Ramos",
            "1 Damager per Dahan. -or- Gather up to 3 Dahan."),
        new Card(CardType.BasegameMinor, "Call to Isolation", 0, Speed.Fast, new Ranges(Source.Presence, 1), TargetProperty.Dahan,
            [Elements.Sun, Elements.Air, Elements.Animal], "Graham Stermberg",
            "Push 1 Explorer / Town per Dahan. -or- Push 1 Dahan."),
        new Card(CardType.BasegameMinor, "Call to Migrate", 1, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Fire, Elements.Air, Elements.Animal], "Graham Stermberg",
            "Gather up to 3 Dahan. Push up to 3 Dahan."),
        new Card(CardType.BasegameMinor, "Call to Tend", 1, Speed.Slow, new Ranges(Source.Presence, 1), TargetProperty.Dahan,
            [Elements.Water, Elements.Plant, Elements.Animal], "Loic Belliau",
            "Remove 1 Blight. -or- Push up to 3 Dahan."),
        new Card(CardType.BasegameMinor, "Quicken the Earth's Struggles", 1, Speed.Fast, new Ranges(Source.SacredSite, 0), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Earth, Elements.Animal], "Lucas Durham",
            "1 Damage to each Town / City. -or- Defend 10."),
        new Card(CardType.BasegameMinor, "Delusions of Danger", 1, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Sun, Elements.Moon, Elements.Air], "Moro Rogers",
            "Push 1 Explorer. -or- 2 Fear."),
        new Card(CardType.BasegameMinor, "Drought", 1, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Sun, Elements.Fire, Elements.Earth], "Nolan Nasser",
            "Destroy 3 Town. 1 Damage to each Town / City. Add 1 Blight. -If you have- 3 Sun: Destroy 1 City."),
        new Card(CardType.BasegameMinor, "Gift of Constancy", 0, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Earth], "Moro Rogers",
            "Target Spirit gains 2 Energy. At end of turn, target Spirit may Reclaim 1 Power Card instead of discarding it. If you target another Spirit, you mal also Reclaim 1 Power Card instead of discarding it."),
        new Card(CardType.BasegameMinor, "Enticing Splendor", 0, Speed.Fast, new Ranges(Source.Presence, 0), TargetProperty.NoBlight,
            [Elements.Sun, Elements.Air, Elements.Plant], "Joshua Wright",
            "Gather 1 Explorer / Town. -or- Gather up to 2 Dahan."),
        new Card(CardType.BasegameMinor, "Entrancing Apparitions", 1, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Moon, Elements.Air, Elements.Water], "Moro Rogers",
            "Defend 2. If no Invaders are present, gather up to 2 Explorer."),
        new Card(CardType.BasegameMinor, "Gift of Living Energy", 0, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Fire, Elements.Plant], "Nolan Nasser",
            "Target Spirit gains 1 Energy, +1 Energy if target Spirit is not yourself. If you have at least 2 SacredSite, target Spirit gains +1 Energy."),
        new Card(CardType.BasegameMinor, "Gift of Power", 0, Speed.Slow, null, TargetSpirit.Any,
            [Elements.Moon, Elements.Water, Elements.Earth, Elements.Plant], "Joshua Wright",
            "Target Spirit gains a Minor Power."),
        new Card(CardType.BasegameMinor, "Gnawing Rootbiters", 0, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Earth, Elements.Animal], "Moro Rogers",
            "Push up to 2 Town."),
        new Card(CardType.BasegameMinor, "Lure of the Unknown", 0, Speed.Fast, new Ranges(Source.Presence, 2), TargetProperty.NoInvaders,
            [Elements.Moon, Elements.Fire, Elements.Air, Elements.Plant], "Lucas Durham",
            "Gather 1 Explorer / Town"),
        new Card(CardType.BasegameMinor, "Purifying Flame", 1, Speed.Slow, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Sun, Elements.Fire, Elements.Air, Elements.Plant], "Jorge Ramos",
            "1 Damage per Blight. If target land is M/S, you may instead remove 1 Blight."),
        new Card(CardType.BasegameMinor, "Rain of Blood", 0, Speed.Slow, new Ranges(Source.SacredSite, 1), TargetProperty.Invaders,
            [Elements.Air, Elements.Water, Elements.Animal], "Kat Birmelin",
            "2 Fear. If target land has at least 2 Town / City, +1 Fear."),
        new Card(CardType.BasegameMinor, "Reaching Grasp", 0, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Air, Elements.Water], "Nolan Nasser",
            "Target Spirit gets +2 Range with all their Powers."),
        // Majors
        new Card(CardType.BasegameMajor, "Accelerated Rot", 4, Speed.Slow, new Ranges(Source.Presence, 2), [Land.Jungle, Land.Wetland],
            [Elements.Sun, Elements.Water, Elements.Plant], "Graham Stermberg",
            "2 Fear. 4 Damage. -If you have- 3 Sun, 2 Water, 3 Plant: +5 Damage. Remove 1 Blight."),
        new Card(CardType.BasegameMajor, "Cleansing Floods", 5, Speed.Slow, new Ranges(Source.Presence, 1, [Land.Wetland]), LandAny,
            [Elements.Sun, Elements.Water], "Nolan Nasser",
            "4 Damage. Remove 1 Blight. -If you have- 4 Water: +10 Damage."),
        new Card(CardType.BasegameMajor, "Pillar of Living Flame", 5, Speed.Slow, new Ranges(Source.SacredSite, 2), LandAny,
            [Elements.Fire], "Jorge Ramos",
            "3 Fear. 5 Damage. If target land is J/W, add 1 Blight. -If you have- 4 Fire: +2 Fear and +5 Damage."),
        new Card(CardType.BasegameMajor, "Poisoned Land", 3, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Earth, Elements.Plant, Elements.Animal], "Nolan Nasser",
            "1 Fear. 7 Damage. Add 1 Blight and destroy all Dahan. -If you have- 3 Earth, 2 Plant, 2 Fire: Per Blight, +1 Fear and +4 Damage."),
        new Card(CardType.BasegameMajor, "Terrifying Nightmares", 4, Speed.Fast, new Ranges(Source.Presence, 2), LandAny,
            [Elements.Moon, Elements.Air], "Loic Belliau",
            "2 Fear. Push up to 4 Explorer / Town. -If you have- 4 Moon: +4 Fear."),
        new Card(CardType.BasegameMajor, "The Trees and Stones Speak of War", 2, Speed.Fast, new Ranges(Source.Presence, 1), TargetProperty.Dahan,
            [Elements.Sun, Elements.Earth, Elements.Plant], "Graham Stermberg",
            "1 Damage and Defend 2 per Dahan in target land. -If you have- 2 Sun, 2 Earth, 2 Plant: You may Push up to 2 Dahan, moving the Defend effect with them"),
        new Card(CardType.BasegameMajor, "Entwined Power", 2, Speed.Fast, null, TargetSpirit.Another,
            [Elements.Moon, Elements.Water, Elements.Plant], "Joshua Wright",
            "You and target Spirit may use each other's Presence to target Powers. Target Spirit gains a Power Card. You take one of the power Cards they did not keep. -If you have- 2 Water, 4 Plant: You and target Spirit each gain 3 Energy and may gift each other 1 Power from hand."),
        new Card(CardType.BasegameMajor, "Paralyzing Frigh", 4, Speed.Fast, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Air, Elements.Earth], "Joshua Wright",
            "4 Fear. Invaders skip all Actions in target land this turn. -If you have- 2 Air, 3 Earth: +4 Fear."),
        new Card(CardType.BasegameMajor, "Powerstorm", 3, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Fire, Elements.Air], "Nolan Nasser",
            "Target Spirit gains 3 Energy. Once this turn, target may Repeat a Power Card by paying its cost again. -If you have- 2 Sun, 2 Fire, 3 Air: Target may repeat up to 3 total Power Cards by paying their costs."),
        new Card(CardType.BasegameMajor, "Talons of Lightning", 6, Speed.Fast, new Ranges(Source.Presence, 1), [Land.Mountain, Land.Wetland],
            [Elements.Fire, Elements.Air], "Nolan Nasser",
            "3 Fear. 5 Damage. -If you have- 3 Fire, 3 Air: Destroy 1 Town in each adjacent land. Increase this power's Range to 3 Range."),
        new Card(CardType.BasegameMajor, "The Jungle Hungers", 3, Speed.Slow, new Ranges(Source.Presence, 1, [Land.Jungle]), LandAny,
            [Elements.Moon, Elements.Plant], "Joshua Wright",
            "Destroy all Explorer and all Town. Destroy all Dahan. -If you have- 2 Moon, 3 Plant: Destroy 1 City. Do not destroy any Dahan."),
        new Card(CardType.BasegameMajor, "The land Thrashes in Furious Pain", 4, Speed.Slow, new Ranges(Source.Presence, 2), TargetProperty.Blight,
            [Elements.Moon, Elements.Fire, Elements.Earth], "Nolan Nasser",
            "2 Damage per Blight in target land. +1 Damage per Blight in adjacent lands. -If you have- 3 Moon, 3 Earth: Repeat on an adjacent land."),
        new Card(CardType.BasegameMajor, "Tsunami", 6, Speed.Slow, new Ranges(Source.SacredSite, 2), Land.Coastal,
            [Elements.Water, Elements.Earth], "Jason Behnke",
            "2 Fear. 8 Damage. Destroy 2 Dahan. -If you have- 3 Water, 2 Earth: +1 Fear, 4 Damage and Destroy 1 Dahan in each other Coastal land on the same board."),
        new Card(CardType.BasegameMajor, "Vigor of the Breaking Dawn", 3, Speed.Fast, new Ranges(Source.Presence, 2), TargetProperty.Dahan,
            [Elements.Sun, Elements.Animal], "Loic Belliau",
            "2 Damage per Dahan in target land. -If you have- 3 Sun, 2 Animal: You may Push up to 2 Dahan. In lands you Pushed Dahan to, 2 Damage per Dahan."),
        new Card(CardType.BasegameMajor, "Vengeance of the Dead", 3, Speed.Fast, new Ranges(Source.Presence, 3), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Animal], "Kat Birmelin",
            "3 Fear. During the rest of this turn, 1 Damage in target land for each Town / City / Dahan destroyed there. -If you have- 3 Animal: Damage from this Power may be dealt into adjacent lands."),
        new Card(CardType.BasegameMajor, "Wrap in Wings of Sunlight", 3, Speed.Fast, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Sun, Elements.Air, Elements.Animal], "Loic Belliau",
            "Move up to 5 Dahan from target land to any land. Defend 5 in that land. -If you have- 2 Sun, 2 Air, 2 Animal: First, Gather up to 3 Dahan."),
        new Card(CardType.BasegameMajor, "Blazing Renewal", 5, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Fire, Elements.Earth, Elements.Plant], "Nolan Nasser",
            "Target Spirit places 2 of their destroyed Presence into a single land, up to 2 Range from your Presence. If any Presence was returned, 2 damage to each Town / City in that land. -If you have- 3 Fire, 3 Earth, 2 Plant: 4 Damage."),
        new Card(CardType.BasegameMajor, "Winds of Rust and Atrophy", 3, Speed.Fast, new Ranges(Source.SacredSite, 3), LandAny,
            [Elements.Air, Elements.Water, Elements.Animal], "Joshua Wright",
            "1 Fear and Defend 6. Replace 1 City with 1 Town or 1 Town with 1 Explorer. -If you have- 3 Air, 3 Water, 2 Animal: Repeat this Power."),
        new Card(CardType.BasegameMajor, "Indomitable Claim", 4, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Sun, Elements.Earth], "Jorge Ramos",
            "Add 1 Presence in target land even if you normally could not due to land type. Defend 20. -If you have- 2 Sun, 3 Earth: 3 Fear if Invaders are present. Invaders skip all Actions in target land this turn."),
        new Card(CardType.BasegameMajor, "Mists of Oblivion", 4, Speed.Slow, new Ranges(Source.Presence, 3), LandAny,
            [Elements.Moon, Elements.Air, Elements.Water], "Nolan Nasser",
            "1 Damage to each Invader in target land. 1 Fear per Town / City destroyed by this Power, to a maximum of 4. -If you have- 2 Moon, 3 Air, 2 Water: +3 Damage."),
        new Card(CardType.BasegameMajor, "Infinite Vitality", 3, Speed.Fast, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Earth, Elements.Plant, Elements.Animal], "Joshua Wright",
            "Dahan have +4 Health while in target land. Whenever Blight would be added to target land, instead leave it on the card. -If you have- 4 Earth: Dahan ignore Damage and Destruction effects. Remove 1 Blight from target or adjacent land."),
        new Card(CardType.BasegameMajor, "Dissolve the bonds", 4, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Fire, Elements.Water, Elements.Animal], "Jorge Ramos",
            "Replace 1 City with 2 Explorer. Replace 1 Town with 1 Explorer. Replace 1 Dahan with 1 Explorer. Push all Explorer from target land to as many different lands as possible. -If you have- 2 Fire, 2 Water, 3 Animal: Before Pushing, Explorer and Town / City do Damage to each other."),

        // Expansion
        // Majors
        new Card(CardType.ExpansionMajor, "Strangling Firevine", 4, Speed.Slow, new Ranges(Source.Presence, 1, [Land.Sand]), LandAny,
            [Elements.Fire, Elements.Plant], "Nolan Nasser",
            "Destroy all Explorer. Add 1 Wilds. Add 1 Wilds in the originating Sands. 1 Damage per Wilds in / adjacent to target land. -If you have- 2 Fire, 3 Plant: +1 Damage per Wilds in / adjacent to target land."),
        new Card(CardType.ExpansionMajor, "Bloodwrap Plague", 4, Speed.Fast, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Water, Elements.Earth, Elements.Animal], "Jorge Ramos",
            "Add 2 Disease. For each Disease in target land, Defend 1 in target and all adjacent lands. -If you have- 2 Earth, 4 Animal: 2 Fear. For each Disease in target land do 1 Damage in target or an adjacent land."),
        new Card(CardType.ExpansionMajor, "Cast down into the Briny Deep", 9, Speed.Slow, new Ranges(Source.SacredSite, 1), [Land.Coastal],
            [Elements.Sun, Elements.Moon, Elements.Water, Elements.Earth], "Jason Behnke",
            "6 Fear. Destroy all Invaders. -If you have- 2 Sun, 2 Moon, 4 Water, 4 Earth: Destroy the board containing target land and everything on that board. All destroyed Blight is removed from the game instead of being returned to the Blight Card."),
        new Card(CardType.ExpansionMajor, "Death Falls Gently from Open Blossoms", 4, Speed.Slow, new Ranges(Source.Presence, 3), [Land.Jungle, Land.Sand],
            [Elements.Moon, Elements.Air, Elements.Plant], "Graham Stermberg",
            "4 Damage. If any Invaders remain, add 1 Disease. -If you have- 3 Air, 3 Plant: 3 Fear. Add 1 Disease to 2 adjacent lands with Invaders."),
        new Card(CardType.ExpansionMajor, "Fire and Flood", 7, Speed.Slow, new Ranges(Source.SacredSite, [1, 2]), LandAny,
            [Elements.Sun, Elements.Fire, Elements.Water], "Jason Behnke",
            "4 Damage in each target land. (Range must be measured from the same SacredSite.) -If you have- 3 Fire: +4 Damage in either target land. 3 Water: +4 Damage in either target land."),
        new Card(CardType.ExpansionMajor, "Grant Hatred a Ravenous Form", 4, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Moon, Elements.Fire], "Nolan Nasser",
            "For each Strife / Blight in target land, 1 Fear and 2 Damage. If this destroys all invaders in target land, add 1 Beasts. -If you have- 4 Moon, 2 Fire: Add 1 Strife in up to 3 adjacent lands."),
        new Card(CardType.ExpansionMajor, "Insatiable Hinger of the Swarm", 4, Speed.Fast, new Ranges(Source.SacredSite, 2), LandAny,
            [Elements.Air, Elements.Plant, Elements.Animal], "Lucas Durham",
            "Add 1 Blight. Add 2 Beasts. Gather up to 2 Beasts. Each Beasts does 1 Fear, 2 Damage to Invaders and 2 Damage to Dahan. Destroy 1 Beasts. -If you have- 2 Air, 4 Animal: Repeat this Power on an adjacent land."),
        new Card(CardType.ExpansionMajor, "Instruments of their own Ruin", 4, Speed.Fast, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Sun, Elements.Fire, Elements.Air, Elements.Animal], "Lucas Durham",
            "Add 1 Strife. Each Invader with Strife deals Damage to other Invaders in target land. -If you have- 4 Sun, 2 Fire, 2 Animal: Instead, if Invaders Ravage in target land, they damage Invaders in adjacent lands instead of Dahan and the land. Dahan in target land do not fight back."),
        new Card(CardType.ExpansionMajor, "Flow like Water, Reach like Air", 2, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Air, Elements.Water], "Joshua Wright",
            "Target Spirit gets +2 Range with all Powers. Target Spirit may Push 1 of their Presence to an adjacent land, bringing up to 2 Explorer, 2 Town and 2 Dahan along with it. -If you have- 2 Air, 2 Water: The moved Presence may also bring along up to 2 City and up to 2 Blight."),
        new Card(CardType.ExpansionMajor, "Pent-Up Calamity", 3, Speed.Fast, new Ranges(Source.Presence, 2), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Earth, Elements.Plant, Elements.Animal], "Joshua Wright",
            "Add 1 Disease and 1 Strife. -or- Remove any number of Beasts / Disease / Strife / Wilds. For each token removed, 1 Fear and 3 Damage. -If you have- 2 Moon, 3 Fire: If you have removed tokens, return up to 2 of them. Otherwise, add 2 Strife."),
        new Card(CardType.ExpansionMajor, "Pyroclastic Flow", 3, Speed.Fast, new Ranges(Source.Presence, 1, [Land.Mountain]), LandAny,
            [Elements.Fire, Elements.Air, Elements.Earth], "Joshua Wright",
            "2 Damage. Destroy all Explorer. If target land is J/W, add 1 Blight. -If you have- 3 Air, 2 Fire, 2 Earth: +4 Damage. Add 1 Wilds."),
        new Card(CardType.ExpansionMajor, "Savage Transformation", 2, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Moon, Elements.Animal], "Loic Belliau",
            "2 Fear. Replace 1 Explorer with 1 Beasts. -If you have- 3 Animal, 2 Moon: Replace 1 additional Explorer with 1 Beasts in either target or adjacent land."),
        new Card(CardType.ExpansionMajor, "Sea Monsters", 5, Speed.Slow, new Ranges(Source.Presence, 1), [Land.Coastal, Land.Wetland],
            [Elements.Water, Elements.Animal], "Moro Rogers",
            "Add 1 Beasts. Per Beasts, 2 Fear and 3 Damage. Per Blight, 1 Damage. -If you have- 3 Water, 3 Animal: Repeat this power."),
        new Card(CardType.ExpansionMajor, "Tigers Hunting", 2, Speed.Fast, new Ranges(Source.Presence, 1, [Land.Jungle]), TargetProperty.NoBlight,
            [Elements.Sun, Elements.Moon, Elements.Animal], "Cari Corene",
            "2 Fear. Add 1 Beasts. Gather up to 1 Beasts. 1 Damage per Beasts. Push up to 2 Beasts. -If you have- 2 Sun, 2 Moon, 3 Animal: 1 Damage in an adjacent land without Blight, and +1 Damage per Beasts there."),
        new Card(CardType.ExpansionMajor, "Unrelenting Growth", 4, Speed.Slow, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Fire, Elements.Water, Elements.Plant], "Joshua Wright",
            "Target Spirit adds 2 Presence and 1 Wilds to a land at 1 Range. -If you have- 3 Sun, 3 Plant: In that land, add 1 additional Wilds and remove 1 Blight. Target Spirit gains a Power Card."),
        new Card(CardType.ExpansionMajor, "Volcanic Eruption", 8, Speed.Slow, new Ranges(Source.Presence, 1, [Land.Mountain]), LandAny,
            [Elements.Fire, Elements.Earth], "Nolan Nasser",
            "6 Fear. 20 Damage. Destroy all Dahan and Beasts. Add 1 Blight. -If you have- 4 Fire, 3 Earth: Destroy all Invaders. Add 1 Wilds. In each adjacent land: 10 Damage. Destroy all Dahan and Beasts. If there are no Blight, add 1 Blight."),
        new Card(CardType.ExpansionMajor, "Sweep into the Sea", 4, Speed.Slow, new Ranges(Source.Presence, 2), LandAny,
            [Elements.Sun, Elements.Air, Elements.Earth], "Joshua Wright",
            "Push all Explorer and Town one land towards the nearest Ocean. -or- If target land is Coastal, destroy all Explorer and Town. -If you have- 3 Sun, 2 Water: Repeat on an adjacent land."),
        new Card(CardType.ExpansionMajor, "Manifest Incarnation", 6, Speed.Slow, new Ranges(Source.Presence, 0), TargetProperty.City,
            [Elements.Sun, Elements.Moon, Elements.Earth, Elements.Animal], "Moro Rogers",
            "6 Fear. +1 Fear for each Town / City and for each of your Presence in target land. Remove 1 City, 1 Town and 1 Explorer. Then Invaders in target land Ravage. -If you have- 3 Sun, 3 Moon: +3 Fear. Invaders do -6 Damage on their Ravage."),
        new Card(CardType.ExpansionMajor, "Smothering Infestation", 3, Speed.Slow, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Water, Elements.Plant], "Joshua Wright",
            "Add 1 Disease. If target land is J/W, 2 Fear and 3 Damage. -If you have- 2 Plant, 2 Water: 1 Damage to each Invader."),
        new Card(CardType.ExpansionMajor, "Twisted Flowers Murmur Ultimatums", 5, Speed.Slow, new Ranges(Source.SacredSite, 1), TargetProperty.Invaders,
            [Elements.Sun, Elements.Moon, Elements.Air, Elements.Earth, Elements.Plant], "Kat Birmelin",
            "4 Fear. Add 1 Strife. If the Terror Level is 2 or higher, remove 2 Invaders. -If you have- 3 Moon, 2 Air, 3 Plant: +3 Fear, before the Terror Level check. 3 Damage."),
        new Card(CardType.ExpansionMajor, "Unlock the Gates of Deepest Power", 4, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Moon, Elements.Fire, Elements.Air, Elements.Water, Elements.Earth, Elements.Plant, Elements.Animal], "Joshua Wright",
            "Target Spirit gains a Major Power by drawing 2 and keeping 1, without having to Forget another Power Card. -If you have- 2 Sun, 2 Moon, 2 Fire, 2 Air, 2 Water, 2 Earth, 2 Plant, 2 Animal: Target Spirit may now play the Major Power they keep by paying half its cost (round up) OR by Forgetting it at the end of turn. It gains all elemental thresholds."),

        // Minor
        new Card(CardType.ExpansionMinor, "Inflame the Fires of Life", 1, Speed.Slow, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Plant, Elements.Animal], "Kat Birmelin",
            "Add 1 Disease. -or'- 1 Fear. Add 1 Strife. -If you have- 3 Animal: You may do both."),
        new Card(CardType.ExpansionMinor, "Fire in the Sky", 1, Speed.Fast, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Sun, Elements.Fire, Elements.Air], "Moro Rogers",
            "2 Fear. Add 1 Strife"),
        new Card(CardType.ExpansionMinor, "Fleshrot Fever", 1, Speed.Slow, new Ranges(Source.Presence, 1), [Land.Jungle, Land.Sand],
            [Elements.Fire, Elements.Air, Elements.Water, Elements.Animal], "Joshua Wright",
            "1 Fear. Add 1 Disease."),
        new Card(CardType.ExpansionMinor, "Gold's Allure", 0, Speed.Slow, new Ranges(Source.Presence, 1), [Land.Mountain],
            [Elements.Fire, Elements.Earth, Elements.Animal], "Lucas Durham",
            "Gather 1 Explorer. and 1 Town. Add 1 Strife."),
        new Card(CardType.ExpansionMinor, "Guardian Serpents", 1, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Moon, Elements.Earth, Elements.Animal], "Moro Rogers",
            "Add 1 Beasts in one of target Spirit's lands. If target Spirit has a SacredSite in that land: Defend 4 there."),
        new Card(CardType.ExpansionMinor, "Here there be Monsters", 0, Speed.Slow, new Ranges(Source.Presence, 0), Land.Inland,
            [Elements.Moon, Elements.Air, Elements.Animal], "Joshua Wright",
            "You may Push 1 Explorer / Town / Dahan. 2 Fear. If target land has any Beasts, 1 Fear."),
        new Card(CardType.ExpansionMinor, "Infested Aquifers", 1, Speed.Slow, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Moon, Elements.Water, Elements.Earth, Elements.Animal], "Nolan Nasser",
            "If target land has any Disease, 1 Damage to each Invader there. -or- If target land is M/W, 1 Fear and add 1 Disease."),
        new Card(CardType.ExpansionMinor, "Poisoned Dew", 1, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Fire, Elements.Water, Elements.Plant], "Cari Corene",
            "Destroy 1 Explorer. If target land is J/W, destroy all Explorer."),
        new Card(CardType.ExpansionMinor, "Portents of Disaster", 0, Speed.Fast, new Ranges(Source.SacredSite, 1), TargetProperty.Invaders,
            [Elements.Sun, Elements.Moon, Elements.Air], "Nolan Nasser",
            "2 Fear. The next time an Invader is destroyed in target land this turn, 1 Fear."),
        new Card(CardType.ExpansionMinor, "Prowling Panthers", 1, Speed.Slow, new Ranges(Source.Presence, 1), [Land.Mountain, Land.Jungle],
            [Elements.Moon, Elements.Fire   , Elements.Animal], "Moro Rogers",
            "1 Fear. Add 1 Beasts. -or- If target land has Beasts, destroy 1 Explorer / Town."),
        new Card(CardType.ExpansionMinor, "Renewing Rain", 1, Speed.Slow , new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Water, Elements.Earth, Elements.Plant], "Nolan Nasser",
            "If target land is J/S, remove 1 Blight. -If you have- 3 Plant: Add 1 Wilds."),
        new Card(CardType.ExpansionMinor, "Rites of the Land's Rejection", 1, Speed.Fast, new Ranges(Source.SacredSite, 2), TargetProperty.Dahan,
            [Elements.Moon, Elements.Fire, Elements.Earth], "Joshua Wright",
            "Invaders do not Build in target land this turn. 1 Fear per Town / City or 1 Fear per Dahan, whichever is less. -or- Push up to 3 Dahan from target land."),
        new Card(CardType.ExpansionMinor, "Pact of the Joined Hunt", 1, Speed.Slow, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Plant, Elements.Animal], "Jorge Ramos",
            "Target Spirit Gathers 1 Dahan into one of their lands. 1 Damage in that land per Dahan present."),
        new Card(CardType.ExpansionMinor, "Razor-Sharp Undergrowth", 1, Speed.Fast, new Ranges(Source.Presence, 0), TargetProperty.NoBlight,
            [Elements.Moon, Elements.Plant], "Cari Corene",
            "Destroy 1 Explorer and 1 Dahan. Add 1 Wilds. Defend 2."),
        new Card(CardType.ExpansionMinor, "Growth through Sacrifice", 0, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Moon, Elements.Fire, Elements.Water, Elements.Plant], "Lucas Durham",
            "Destroy 1 of your Presence. Target Spirit removes 1 Blight from one of their lands. -or- Adds 1 Presence to one of their lands. -If you have- 2 Sun: They may do both, in the same land."),
        new Card(CardType.ExpansionMinor, "Scour the Land", 1, Speed.Slow, new Ranges(Source.SacredSite, 2), LandAny,
            [Elements.Air, Elements.Earth], "Joshua Wright",
            "Destroy 3 Town and all Explorer. Add 1 Blight. -If you have- 3 Air: This power may be Fast."),
        new Card(CardType.ExpansionMinor, "Sky stretches to Shore", 1, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Air, Elements.Water, Elements.Earth], "Joshua Wright",
            "This turn, target Spirit may use 1 Slow Power as if it were Fast, or vice versa. Target Spirit gains +3 Range for targeting Coast lands only."),
        new Card(CardType.ExpansionMinor, "Swarming Wasps", 0, Speed.Fast, new Ranges(Source.Presence, 1), TargetProperty.NoBlight,
            [Elements.Fire, Elements.Air, Elements.Animal], "Joshua Wright",
            "Add 1 Beasts. -or- If target land has Beasts, Push up to 2 Explorer."),
        new Card(CardType.ExpansionMinor, "Absorb Corruption", 1, Speed.Slow, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Sun, Elements.Earth, Elements.Plant], "Nolan Nasser",
            "Gather 1 Blight. -or- Pay 1 Energy to remove 1 Blight. -If you have- 2 Plant: You may do both."),
        new Card(CardType.ExpansionMinor, "Animated Wrackroot", 0, Speed.Slow, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Plant], "Joshua Wright",
            "1 Fear. Destroy 1 Explorer. -or- Add 1 Wilds."),
        new Card(CardType.ExpansionMinor, "Promises of Protection", 0, Speed.Fast, new Ranges(Source.SacredSite, 2), LandAny,
            [Elements.Sun, Elements.Earth, Elements.Animal], "Lucas Durham",
            "Gather up to 2 Dahan. Dahan have +2 Health while in target land."),
        new Card(CardType.ExpansionMinor, "Call to Ferocity", 0, Speed.Slow, new Ranges(Source.Presence, 1), TargetProperty.Invaders,
            [Elements.Sun, Elements.Fire, Elements.Earth], "Joshua Wright",
            "Gather up to 3 Dahan. -or- If target land has Dahan, 1 Fear and Push 1 Explorer and 1 Town."),
        new Card(CardType.ExpansionMinor, "Call to Trade", 1, Speed.Fast, new Ranges(Source.Presence, 2), TargetProperty.Dahan,
            [Elements.Air, Elements.Water, Elements.Earth, Elements.Plant], "Kat Birmelin",
            "You may Gather 1 Dahan. If the Terror Level is 2 or lower, Gather 1 Town and the first Ravage in target land this turn becomes a Build there instead."),
        new Card(CardType.ExpansionMinor, "Confunding Mists", 1, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Air, Elements.Water], "Loic Belliau",
            "Defend 4. -or- Each Invader added to target land this turn may be immediately Pushed to any adjacent land."),
        new Card(CardType.ExpansionMinor, "Cycles of Time and Tide", 1, Speed.Fast, new Ranges(Source.Presence, 1), [Land.Coastal],
            [Elements.Sun, Elements.Moon, Elements.Water], "Joshua Wright",
            "If there are Dahan, add 1 Dahan. If there are no Dahan, remove 1 Blight."),
        new Card(CardType.ExpansionMinor, "Disorienting Landscape", 1, Speed.Fast, new Ranges(Source.SacredSite, 2), LandAny,
            [Elements.Moon, Elements.Air, Elements.Plant], "Nolan Nasser",
            "Push 1 Explorer. If target land is M/J, add 1 Wilds."),
        new Card(CardType.ExpansionMinor, "Elusive Ambushes", 1, Speed.Fast, new Ranges(Source.Presence, 1), TargetProperty.Dahan,
            [Elements.Sun, Elements.Fire, Elements.Water], "Nolan Nasser",
            "1 Damage. -or- Defend 4."),
        new Card(CardType.ExpansionMinor, "Tormenting Rotflies", 1, Speed.Slow, new Ranges(Source.Presence, 2), [Land.Sand, Land.Wetland],
            [Elements.Air, Elements.Plant, Elements.Animal], "Kat Birmelin",
            "Add 1 Disease. -or- If target land has Invaders, 2 Fear. If Disease is present, +1 Fear. If Blight is present, +1 Fear."),
        new Card(CardType.ExpansionMinor, "Twilight Fog brings Madness", 0, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Sun, Elements.Moon, Elements.Air, Elements.Water], "Loic Belliau",
            "Add 1 Strife. Push 1 Dahan. Each remaining Dahan takes 1 Damage."),
        new Card(CardType.ExpansionMinor, "Teeming Rivers", 1, Speed.Slow, new Ranges(Source.SacredSite, 2), [Land.Mountain, Land.Wetland],
            [Elements.Sun, Elements.Water, Elements.Plant, Elements.Animal], "Lucas Durham",
            "If target land has no Blight, add 1 Beasts. If target land has exactly 1 Blight, remove it."),
        new Card(CardType.ExpansionMinor, "Spur on with Words of Fire", 1, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Fire, Elements.Air], "Nolan Nasser",
            "If you target a Spirit other than yourself, they gain +1 Energy. Target Spirit may immediately play another Power Card by paying its cost. (If it is Slow, it does not resolve until later.)"),

        // Spirit Cards
        new Card(Unique.SharpFangsBehindTheLeaves, "Prey on the Builders", 1, Speed.Fast, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Animal], "Moro Rogers",
            "You may Gather 1 Beasts. If target land has Beasts, Invaders do not Build there this turn."),
        new Card(Unique.SharpFangsBehindTheLeaves, "Teeth Gleam from Darkness", 1, Speed.Slow, new Ranges(Source.Presence, 1, [Land.Jungle]), TargetProperty.NoBlight,
            [Elements.Moon, Elements.Plant, Elements.Animal], "Moro Rogers",
            "1 Fear. Add 1 Beasts. -or- If target land has both Beasts and Invaders: 3 Fear."),
        new Card(Unique.SharpFangsBehindTheLeaves, "Too near the Jungle", 0, Speed.Slow, new Ranges(Source.Presence, 1, [Land.Jungle]), LandAny,
            [Elements.Plant, Elements.Animal], "Moro Rogers",
            "1 Fear. Destroy 1 Explorer."),
        new Card(Unique.SharpFangsBehindTheLeaves, "Terrifying Chase", 1, Speed.Slow, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Sun, Elements.Animal], "Moro Rogers",
            "Push 2 Explorer / Town / Dahan. Push another 2 Explorer / Town / Dahan per Beasts in target land. If you Pushed any Invaders, 2 Fear."),
        new Card(Unique.KeeperOfTheForbiddenWilds, "Towering Wrath", 3, Speed.Slow, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Sun, Elements.Fire, Elements.Plant], "Joshua Wright",
            "2 Fear. 2 Damage per your SacredSite in or adjacent to target land. Destroy all Dahan."),
        new Card(Unique.KeeperOfTheForbiddenWilds, "Regrow from Roots", 1, Speed.Slow, new Ranges(Source.Presence, 1), [Land.Jungle, Land.Wetland],
            [Elements.Water, Elements.Earth, Elements.Plant], "Joshua Wright",
            "If there are 2 Blight or fewer in target land, remove 1 Blight."),
        new Card(Unique.KeeperOfTheForbiddenWilds, "Boon of Growing Power", 1, Speed.Slow, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Moon, Elements.Plant], "Joshua Wright",
            "Target Spirit gains a Power Card." +
            "If you target another Spirit, they also gain 1 Energy."),
        new Card(Unique.KeeperOfTheForbiddenWilds, "Sacrosanct Wilderness", 2, Speed.Fast, new Ranges(Source.Presence, 1), TargetProperty.NoBlight,
            [Elements.Sun, Elements.Earth, Elements.Plant], "Joshua Wright",
            "Push 2 Dahan. 2 Damage per Wilds in target land. -or- Add 1 Wilds."),
    ];
}
