// This file contains material owned by Greater Than Games, LLC.

/// <reference path="types.ts" />

namespace DB {
    import ChoiceEventCard = Types.ChoiceEventCard;
    import ChoiceDesc = Types.ChoiceDesc;
    import ChoiceCost = Types.ChoiceCost;
    import StageEventCard = Types.StageEventCard;
    import TerrorLevelEventCard = Types.TerrorLevelEventCard;
    import HealthyBlightedLandEventCard = Types.HealthyBlightedLandEventCard;
    import EventDesc = Types.EventDesc;
    import AdversaryEvent = Types.AdversaryEvent;
    import Adversary = Types.Adversary;
    const { PowerCard, Unique, Speed, Ranges, Source, LandAny, Elements, TargetSpirit, TargetProperty, Land, PowerDeckType, FearCard, FearType } = Types;

    export enum TokenEvent {
        // Beasts
        BeastsAttack = "Beasts Attack: Each Beasts deals 2 Damage. Remove any token that destroys Town / City.",
        BeastsFindNewHomes = "Beasts Find New Homes: On Each Board: Push 1 Beasts to an adjacent land without Blight. 1 Fear if Invaders are present there.",
        BeastsProwl = "Beasts Prowl: Each Beasts generates 1 Fear if Invaders are present, and moves to an adjacent land if not.",
        PreyOnTheUnwary = "Prey on the Unwary: Each Beasts destroys 1 Explorer. Add 1 Beasts to a board without one.",
        SavageFrenzy = "Savage Frenzy: Each Beasts destroys 1 Explorer and deals 2 Damage.",
        BeastsOfTheJungle = "Beasts of the Jungle: On Each Board: Add 1 Beasts to a Jungle without Blight. 1 Fear if Invaders are present.",
        DistantHunt = "Distant Hunt: On Each Board: Push 1 Beasts to an adjacent land with no Blight. It deals 1 Damage there.",
        BeastsProvoked = "Beasts Provoked: On Each Board: Add 1 Beasts to a land without Blight that has Town.",
        // Disease
        NewDiseases = "New Diseases: On half of the boards (rounding up) add 1 Disease to a land with both Dahan and Invaders. Do 2 Damage to Dahan there.",
        LingeringPlagues = "Lingering Plagues: On Each Board: Add 1 Disease. Ignore Disease during Builds this Invader Phase.",
        WheezelungOutbreak = "Wheezelung Outbreak: On Each Board: Add Disease to the Jungle / Wetland with the most Town / City (minimum 1).",
        GrimToll = "Grim Toll: On Each Board: Choose a land with Disease. In that land, do 2 Damage to Invaders and 2 Damage to Dahan.",
        SandfeverOutbreak = "Sandfever Outbreak: On Each Board: Add 1 Disease to the Sands or Mountains with the most Town / City (minimum 1).",
        // Disease / Strife
        Stricken = "Stricken: Invaders do not Ravage in lands with Disease or Strife.",
    }

    export enum DahanEvent {
        CannyDefense = "Canny Defense: During Ravage, in every land, Defend 1 per Dahan in the land.",
        OfferingsOfPatternAndDance = "Offerings of Pattern and Dance: Each Spirit with at least 2 Dahan among all its lands gains 1 Energy.",
        ReclaimTerritory = "Reclaim Territory: Each player may Push 1 Dahan to an adjacent land, doing 1 Damage there.",
        SpiritSpeakersSolveRiddlesOfPower = "Spirit-Speakers Solvel Riddles of Power: Each Spirit with at least 4 Dahan among its lands gains a Minor Power.",
        RaidsInForce = "Raids in Force: Each Spirit chooses a differend land where Dahan outnumber Town / City. Each Dahan there does 1 Damage.",
        SeekASaferHome = "Seek a Safer Home: On Each Board: Push 2 Dahan from a land with Beasts / Disease / Wilds to a land without any of those tokens.",
        ForsakeTheBarrenLand = "Forsake the Barren Land: On Each Board: Push 2 Dahan from a land with Blight to a land without Blight.",
        Retreat = "Retreat: On Each Board: Push 2 Dahan from a land with City to a land without City.",
        TendTheLand = "Tend the Land: On Each Board: Remove 1 Blight from a land with at least 2 Dahan.",
        ComingOfAge = "Coming of Age: On Each Board: Add 1 Dahan to a Mountain or Sands with Dahan.",
        RecklessOffensive = "Reckless Offensive: On Each Board: Choose a land with at least 2 Dahan and at least 2 Town / City. Each Dahan destroys 1 Town / City. Add 1 Blight.",
        RouseTheSpirits = "Rouse the Spirits: Each Spirit with at least 3 Dahan among all its lands may use a Slow Power now (instead of later).",
        FierceMein = "Fierce Mein: 1 Fear per land with Invaders where Dahan outnumber Town / City.",
        TrapsAndSnares = "Traps and Snares: On Each Board: Add 1 Wilds to a land with Dahan.",
        DriveOffTheInterlopers = "Drife off the Interlopers: Each player may Push 1 Explorer / Town from a land with Dahan.",
        AidTheUprising = "Aid the Uprising: Invaders with Strife take 1 Damage per Dahan present. Add 1 Dahan per Town / City this destroys.",
    }

    class Events {
        // Choice
        public static LetThePlantsDieAndTheLandWither = new ChoiceDesc("Let the Plants Die and the Land Wither", null,
            ["For each board, discard the top Minor Power. If it lacks Water, add 1 Blight to a sands.",
                "Town, City and Dahan have -1 Health (minimum 1) until the end of the turn."]);
        public static ActToEaseTheDrought = new ChoiceDesc("Act to ease the Drought", new ChoiceCost(4, "player", Elements.Water),
            ["Each Spirit may add 1 Presence to one of their lands with Dahan."]);
        public static SpurnTheInvaders = new ChoiceDesc("Spurn the Invaders", null,
            ["On Each Board: 2 Damage to Dahan in a land with Town / City.",
                "On Each Board: Add 1 Blight to a land with at least 2 Town / City.",
                "Town / City have -1 Health (to a minimum of 1) until the end of the turn."]);
        public static TeachTheInvaders = new ChoiceDesc("Teach the Invaders", null,
            ["On Each Board: add 1 Town to a land with Dahan.", "The next normal Ravage becomes a Build (This could be on a future turn.)"]);
        public static LetTheInvasiveSpeciesBloom = new ChoiceDesc("Let the Invasive Species Bloom", null,
            ["For each board, discard the top Minor Power. If it is Fast, add 1 Blight to a land with Town / City.",
                "After resolving this card, return it to the Event Deck under teh top 2 cards."]);
        public static TransmuteTheWorstOfTheSpecies = new ChoiceDesc("Transmute the Worst of the Species", new ChoiceCost(4, "player", Elements.Moon),
            ["1 Fear per player. On Each Board add 1 Beasts to a land with Town / City."]);
        public static AllowTheAttacks = new ChoiceDesc("Allow the Attacks", null,
            ["For each board, discard the top Major Power. Deal its Energy in Damage to Invaders and the land in the Coastal land with the most Town / City (minimum 1). Defend reduces this Damage."]);
        public static HelpRepelTheNewcomers = new ChoiceDesc("Help Repel the Newcomers", new ChoiceCost(1, "player", null),
            ["Add a Fear Card to the top of the Fear Deck."]);
        public static LetTheIslandsStrengthRepulseThem = new ChoiceDesc("Let the Island's Strength Repulse Them", null,
            ["Each SacredSite Pushes 1 Explorer / Town to an adjacent land.", "Remove 1 Blight per player from the Blight Card, returning it to the box."]);
        public static GuardThemYourselfForWellOrIll = new ChoiceDesc("Guard them Yourself, for Well or Ill", new ChoiceCost(3, "land where you do damage", Elements.Fire),
            ["In each land with SacredSite and Invaders: Either do 2 Damage. -or- Destroy 1 Presence from each Spirit."]);
        public static StaySteadyAndSlow = new ChoiceDesc("Stay Steady and Slow", null,
            ["Discard the Power Card.", "Gain 1 Energy, plus the card's printed Energy cost."]);
        public static WorkToMatchTheirPace = new ChoiceDesc("Work to Match their Pace", null,
            ["Pay 3 Energy -or- destroy 2 Presence.", "You may choose to resolve the Power Card now. (Instead of during the Slow Phase.)"]);
        public static IgnoreTheirContactWithTheDahan = new ChoiceDesc("Ignore their Contact with the Dahan", null,
            ["For each board, discard the top Minor Power. If it has Sun, Push 1 Explorer from a land with Dahan. Otherwise. replace 1 Dahan with 1 Town.",
                "After resolving this card, return it to the Event Deck under the top 2 cards."]);
        public static CurseTheTonguesOfTheForeigners = new ChoiceDesc("Curse the Tongues of the Foreigners", new ChoiceCost(4, "player", Elements.Sun),
            ["Each Spirit: Add 1 Disease to a land with City.", "2 Fear per Player.", "During the next normal Ravage, City do +3 Damage."]);
        public static LetThemRampageUntoDeath = new ChoiceDesc("Let them Rampage unto Death", null,
            ["Each Beasts destroys 1 Dahan.", "Remove 1 Beasts from each board."]);
        public static GuideTheMadness = new ChoiceDesc("Guide the Madness", new ChoiceCost(3, "Beasts you decide to keep on the island. (min 3 Energy).", Elements.Animal),
            ["Remove any number of Beasts.", "Each Spirit may Push 1 Beasts to an adjacent land"]);
        public static IgnoreTheCuriosity = new ChoiceDesc("Ignore the Curiosity", null,
            ["Return the top card of the Invader Deck to the box. (Skip cards specially placed during Setup.)", "On Each Board: Add 1 Town to a land without one."]);
        public static WeaveLiesInTheMindsOfTheirObservers = new ChoiceDesc("Weave Lies in the Minds of their Observers", new ChoiceCost(4, "player", Elements.Air),
            ["Return the top Fear Card to the Box.", "During the next normal Ravage, each Town / City does +1 Damage."]);

        // Stage Events
        public static SeekingTheInterior = new EventDesc("Seeking the Interior", "In each Coastal land, Push 1 Explorer one land Inland.");
        public static LocalDiaspora = new EventDesc("Local Diaspora", "In the single land with the most Invaders, Push 1 Explorer / Town to each adjacent land.");
        public static WaveOfReconnaissance = new EventDesc("Wave of Reconnaissance", "When Exploring: Add 1 additional Explorer to each land Explored.");
        public static Urbanization = new EventDesc("Urbanization", "In each land with at least 2 Town, replace half the Town (rounding up) with City.");
        public static InterestingDiscoveries = new EventDesc("Interesting Discoveries",
            "On Each Board: Choose a SacredSite. Gather 1 Explorer into its land, and add 1 additional Explorer.");
        public static IncreasingAggression = new EventDesc("Increasing Aggression", "Invaders do +1 Damage (per land) when Ravaging.");
        public static StrangeTalesAttractExplorers = new EventDesc("Strange Tales attract Explorers",
            "Now: 1 Fear per Spirit that has at least 1 SacredSite. After advancing Invader Cards: Add 1 Explorer to each land with SacredSite.");
        public static Fortification = new EventDesc("Fortification",
            "After advancing Invader Cards: Invaders Build in one terrain not shown under any Invader Action. (If there's no such terrain, nothing happens.)");
        public static SmallUprising = new EventDesc("Small Uprising",
            "On Each Board: add 1 Strife to 1 Town. After finishing this Event Card, draw another one, then return this card to the Event Deck as per Setup.");
        public static Rebellion = new EventDesc("Rebellion!",
            "On Each Board: Destroy 1 Town. Add 1 Strife to any 2 Town / City. Then, every Invader takes 1 Damage per Strife it has. After finishing this Event card, draw another one. This card is discarded.");

        // Terror Level
        public static CulturalAssimilation = new EventDesc("Cultural Assimilation",
            "On Each Board: In a land with exactly 1 Dahan that has or is adjacent to a City, replace that Dahan with 1 Town.");
        public static ReprisalAgainstTheDahan = new EventDesc("Reprisal Against the Dahan",
            "On Each Board: choose a land with Dahan and Town / City. Invaders do 3 Damage to Dahan there, ignoring Defend Powers.");
        public static InvestigationOfDangers = new EventDesc("Investigation of Dangers", "On Each Board: Add 1 Explorer to a land without Invaders or Dahan.");
        public static DestroyTheUnnatural = new EventDesc("Destroy the unnatural!", "Invaders do +3 Damage (per land) when Ravaging in lands with Presence.");
        public static DistantExploration = new EventDesc("Distant Exploration", "Invaders Explore at +1 distance.");
        public static FearfulMobs = new EventDesc("Fearful Mobs", "When Ravaging, Invaders do +3 Damage (per land) in lands with 3 or more Invaders.");

        // Healthy / Blighted Land
        public static PuttingDownRoots = new EventDesc("Putting down Roots",
        "On an Inland Land on Each Board: Replace 1 Explorer with 1 Town.");
        public static TheCenterCrumbles = new EventDesc("The Center Crumbles",
            "On Each Board With Invaders: Add 1 Blight to an Inland land. Spirits may prevent this on any / all boards by destroying 3 Presence from each board to be protected.");
        public static SearchForNewLands = new EventDesc("Search for new Lands",
            "In Each Land With at least 2 Explorer: Push 1 Explorer to an adjacent land without Invaders.");
        public static DevastatedShores = new EventDesc("Devastated Shores",
            "On Each Board With Invaders: Add 1 Blight to a Coastal land. Spirits may prevent this on any / all boards by destroying 2 Presence from each board to be protected.");
        public static InvadersSurgeInland = new EventDesc("Invaders Surge Inland",
            "On a Coastal land on Each Board: Move 1 Town one or two lands inland.");
        public static WideningDestruction = new EventDesc("Widening Destruction",
            "On Each Board: add 1 Blight to a land with / adjacent to Town / City. Spirits may prevent this on any / all boards by destroying 2 Presence from each board to be protected.");
        public static TightKnitCommunities = new EventDesc("Tight-Knit Communities",
            "For the rest of this turn, Town / City have +1 Health.");
        public static BlightSpreads = new EventDesc("Blight Spreads",
            "On Each Board: Add 1 Blight to a land adjacent to a land with Blight. Spirits may prevent this on any / all boards by destroying 2 Presence from each board to be protected.");
        public static WellPreparedExplorers = new EventDesc("Well-Prepared Explorers",
            "For the rest of this turn, Explorer have +1 Health.");
        public static PopulationRises = new EventDesc("Population Rises",
            "On Each Board: Add 1 Town to a land with Explorer / Town.");
        public static PowerFades = new EventDesc("Power Fades",
            "Eac Spirit chooses independently to: Destroy 2 of their Presence, -or- Forget 2 of their Powers, -or- Take 1 Blight from the Blight Card and remove it from the game.");
        public static UrbanDevelopment = new EventDesc("Urban Development",
            "During the next normal Ravage, each City does +2 Damage. (If there is no Ravage this phase, leave this card by the Ravage space until one happens.)");
        public static FesteringPitsOfBlight = new EventDesc("Festering Pits of Blight",
            "On Each Board With Invaders: Add 1 Blight to a land with at least 2 Blight, bot do not cascade.");
        public static HeavyFarming = new EventDesc("Heavy Farming",
            "During the next normal Ravage, each Town does +1 Damage. (If there is no Ravage this phase, leave this card by the Ravage space until one happens.)");
        public static OvercrowdedCities = new EventDesc("Overcrowded Cities",
            "On Each Board with City: Add 1 Blight to a land with City. Spirits may prevent this on any / all boards by destroying 2 Presence from each board to be protected.");
        public static PromisingFarmland = new EventDesc("Promising Farmland",
            "When Exploring, once per board, place 1 Town instead of 1 Explorer.");
        public static NewCashCropsTakeHold = new EventDesc("New Cash Crops Take Hold",
            "Invaders immediately Ravage in 1 terrain type not showing under any Invader Action. Spirits may prevent this Ravage on any / all boards by Destroying  Presence from each board to be protected.");
    }

    export const CARDS = [
        // Spirit Cards
        new PowerCard(Unique.LightngingsSwiftStrike, "Shatter Homesteads", 2, Speed.Slow, new Ranges(Source.SacredSite, 2), LandAny,
            [Elements.Fire, Elements.Air], "Rocky Hammer",
            "1 Fear. Destroy 1 Town."),
        new PowerCard(Unique.LightngingsSwiftStrike, "Raging Storm", 3, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Fire, Elements.Air, Elements.Water], "Rocky Hammer",
            "1 Damage to each Invader."),
        new PowerCard(Unique.LightngingsSwiftStrike, "Lightning's Boon", 1, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Fire, Elements.Air], "Rocky Hammer",
            "Target Spirit may use up to 2 Slow Powers as if they were Fast Powers this turn"),
        new PowerCard(Unique.LightngingsSwiftStrike, "Harbingers of the Lightning", 0, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Fire, Elements.Air], "Rocky Hammer",
            "Push up to 2 Dahan. 1 Fear if you pushed any Dahan into a land with Town / City"),
        new PowerCard(Unique.RiverSurgesInSunlight, "Flash Floods", 2, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Sun, Elements.Water], "Nolan Nasser",
            "1 Damage. If target land is Coastal, +1 Damage."),
        new PowerCard(Unique.RiverSurgesInSunlight, "Wash Away", 1, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Water, Elements.Earth], "Nolan Nasser",
            "Push up to 3 Explorer / Town"),
        new PowerCard(Unique.RiverSurgesInSunlight, "Boon of Vigor", 0, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Water, Elements.Plant], "Nolan Nasser",
            "If you target yourself, gain 1 Energy. If you target another Spirit, they gain 1 Energy per Power Card they played this turn."),
        new PowerCard(Unique.RiverSurgesInSunlight, "River's Bounty", 0, Speed.Slow, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Sun, Elements.Water, Elements.Animal], "Nolan Nasser",
            "Gather up to 2 Dahan. If there are now at least 2 Dahan, add 1 Dahan and gain 1 Energy."),
        new PowerCard(Unique.ShadowsFlickerLikeFlame, "Concealing Shadows", 0, Speed.Fast, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Moon, Elements.Air], "Nolan Nasser",
            "1 Fear. Dahan take no damage from Ravaging Invaders this turn."),
        new PowerCard(Unique.ShadowsFlickerLikeFlame, "Favors Called Due", 1, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Moon, Elements.Air, Elements.Animal], "Nolan Nasser",
            "Gather up to 4 Dahan. If Invaders are present and Dahan now outnumber them, 3 Fear."),
        new PowerCard(Unique.ShadowsFlickerLikeFlame, "Mantle of Dread", 1, Speed.Slow, null, TargetSpirit.Any,
            [Elements.Moon, Elements.Fire, Elements.Air], "Nolan Nasser",
            "2 Fear. Target Spirit may Push 1 Explorer and 1 Town from one of their lands."),
        new PowerCard(Unique.ShadowsFlickerLikeFlame, "Crops Wither and Fade", 1, Speed.Slow, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Plant], "Nolan Nasser",
            "2 Fear. Replace 1 Town with 1 Explorer. -or- Replace 1 City with 1 Town."),
        new PowerCard(Unique.VitalStrengthOfTheEarth, "Guard the Healing Land", 3, Speed.Fast, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Water, Elements.Earth, Elements.Plant], "Sydni Kruger",
            "Remove 1 Blight. Defend 4."),
        new PowerCard(Unique.VitalStrengthOfTheEarth, "A Year of Perfect Stillness", 3, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Sun, Elements.Earth], "Sydni Kruger",
            "Invaders skipp all Actions in target land this turn."),
        new PowerCard(Unique.VitalStrengthOfTheEarth, "Rituals of Destruction", 3, Speed.Slow, new Ranges(Source.SacredSite, 1), TargetProperty.Dahan,
            [Elements.Sun, Elements.Moon, Elements.Fire, Elements.Earth, Elements.Plant], "Sydni Kruger",
            "2 Damage. If target land has at least 3 Dahan, +3 Damage and 2 Fear."),
        new PowerCard(Unique.VitalStrengthOfTheEarth, "Draw of the Fruitful Earth", 1, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Earth, Elements.Plant, Elements.Animal], "Sydni Kruger",
            "Gather up to 2 Explorer. Gather up to 2 Dahan."),
        new PowerCard(Unique.Thunderspeaker, "Manifestation of Power and Glory", 3, Speed.Slow, new Ranges(Source.Presence, 0), TargetProperty.Dahan,
            [Elements.Sun, Elements.Fire, Elements.Air], "Loic Belliau",
            "1 Fear. Each Dahan deals damage equal to the number of your Presence in target land."),
        new PowerCard(Unique.Thunderspeaker, "Words of Warning", 1, Speed.Fast, new Ranges(Source.Presence, 1), TargetProperty.Dahan,
            [Elements.Sun, Elements.Air, Elements.Animal], "Loic Belliau",
            "Defend 3. During Ravage, Dahan in target land deal damage simultaneously with Invaders."),
        new PowerCard(Unique.Thunderspeaker, "Sudden Ambush", 2, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Fire, Elements.Air, Elements.Animal], "Loic Belliau",
            "You may Gather 1 Dahan. Each Dahan destroys 1 Explorer."),
        new PowerCard(Unique.Thunderspeaker, "Voice of Thunder", 0, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Sun, Elements.Air], "Loic Belliau",
            "Push up to 4 Dahan. -or- If Invaders are Present, 2 Fear."),
        new PowerCard(Unique.OceansHungryGrasp, "Call of the Deeps", 0, Speed.Fast, new Ranges(Source.Presence, 0), Land.Coastal,
            [Elements.Moon, Elements.Air, Elements.Water], "Joshua Wright",
            "Gather 1 Explorer. If target land is the Ocean, you may Gather another Explorer."),
        new PowerCard(Unique.OceansHungryGrasp, "Grasping Tide", 1, Speed.Fast, new Ranges(Source.Presence, 1), Land.Coastal,
            [Elements.Moon, Elements.Water], "Joshua Wright",
            "2 Fear. Defend 4."),
        new PowerCard(Unique.OceansHungryGrasp, "Swallow the Land-Dwellers", 0, Speed.Slow, new Ranges(Source.Presence, 0), Land.Coastal,
            [Elements.Water, Elements.Earth], "Joshua Wright",
            "Drown 1 Explorer, 1 Town, and 1 Dahan."),
        new PowerCard(Unique.OceansHungryGrasp, "Tidal Boon", 1, Speed.Slow, null, TargetSpirit.Another,
            [Elements.Moon, Elements.Water, Elements.Earth], "Joshua Wright",
            "Target Spirit gains 2 Energy and may Push 1 Town and up to 2 Dahan from one of their lands. If Dahan are pushed to your ocean, you may move them to any Coastal land instead of Drowning them."),
        new PowerCard(Unique.BringerOfDreamsAndNightmares, "Predatory Nightmares", 2, Speed.Slow, new Ranges(Source.SacredSite, 1), TargetProperty.Invaders,
            [Elements.Moon, Elements.Fire, Elements.Earth, Elements.Animal], "Shane Tyree",
            "2 Damage. Push up to 2 Dahan. (When your powers would destroy Invaders, instead they generate Fear and/or Push those Invaders.)"),
        new PowerCard(Unique.BringerOfDreamsAndNightmares, "Dread Apparitions", 2, Speed.Fast, new Ranges(Source.Presence, 1), TargetProperty.Invaders,
            [Elements.Moon, Elements.Air], "Shane Tyree",
            "When Powers generate Fear in target land, Defend 1 per Fear. 1 Fear. (Fear from To Dream a Thousand Death counts. Fear from Destroying Town / City does not."),
        new PowerCard(Unique.BringerOfDreamsAndNightmares, "Call on Midnight's Dreams", 0, Speed.Fast, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Moon, Elements.Animal], "Shane Tyree",
            "If target land has Dahan, gain a Major Power. If you Forget this Power, gain Energy equal to Dahan and you may play the Major Power immediately, paying its cost. -or- If Invaders are present, 2 Fear."),
        new PowerCard(Unique.BringerOfDreamsAndNightmares, "Dreams of the Dahan", 0, Speed.Fast, new Ranges(Source.Presence, 2), LandAny,
            [Elements.Moon, Elements.Air], "Shane Tyree",
            "Gather up to 2 Dahan. -or- If target land has Town / City, 1 Fear for each Dahan, to a maximum of 3 Fear."),
        new PowerCard(Unique.ASpreadOfRampantGreen, "Overgrow in a Night", 2, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Moon, Elements.Plant], "Jorge Ramos",
            "Add 1 Presence. -or- If target land has your Presence and Invaders, 3 Fear."),
        new PowerCard(Unique.ASpreadOfRampantGreen, "Gift of Proliferation", 1, Speed.Fast, null, TargetSpirit.Another,
            [Elements.Moon, Elements.Plant], "Jorge Ramos",
            "Target Spirit adds 1 Presence up to 1 Range from their Presence."),
        new PowerCard(Unique.ASpreadOfRampantGreen, "Fields Choked with Growth", 0, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Sun, Elements.Water, Elements.Plant], "Jorge Ramos",
            "Push 1 Town. -or- Push 3 Dahan"),
        new PowerCard(Unique.ASpreadOfRampantGreen, "Stem the Flow of Fresh Water", 0, Speed.Slow, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Water, Elements.Plant], "Jorge Ramos",
            "1 Damage to 1 Town or 1 City. If target land is M/S, instead, 1 Damage to each Town / City."),

        // Colored Corners
        // green corner
        new PowerCard(PowerDeckType.BasegameMinor, "Savage Mawbeasts", 0, Speed.Slow, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Fire, Elements.Animal], "Cari Corene",
            "If target land is J/W, 1 Fear and 1 Damage. -If you have- 3 Animal: 1 Damage."),
        new PowerCard(PowerDeckType.BasegameMinor, "Voracious Growth", 1, Speed.Slow, new Ranges(Source.SacredSite, 1), [Land.Jungle, Land.Wetland],
            [Elements.Water, Elements.Plant], "Cari Corene",
            "2 Damage. -or- Remove 1 Blight."),
        new PowerCard(PowerDeckType.BasegameMinor, "Rouse the Trees and Stones", 1, Speed.Slow, new Ranges(Source.SacredSite, 1), TargetProperty.NoBlight,
            [Elements.Fire, Elements.Earth, Elements.Plant], "Jorge Ramos",
            "2 Damage. Push 1 Explorer."),
        // blue corner
        new PowerCard(PowerDeckType.BasegameMinor, "Encompassing Ward", 1, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Water, Elements.Earth], "Jorge Ramos",
            "Defend 2 in every land where target Spirit has Presence."),
        new PowerCard(PowerDeckType.BasegameMinor, "Song of Sanctity", 1, Speed.Slow, new Ranges(Source.Presence, 1), [Land.Mountain, Land.Jungle],
            [Elements.Sun, Elements.Water, Elements.Plant], "Nolan Nasser",
            "If target land has 1 Explorer, Push all Explorer. Otherwise, remove 1 Blight."),
        new PowerCard(PowerDeckType.BasegameMinor, "Uncanny Melting", 1, Speed.Slow, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Sun, Elements.Moon, Elements.Water], "Joshua Wright",
            "If Invaders are present, 1 Fear. If target land is S/W, remove 1 Blight"),
        // red corner
        new PowerCard(PowerDeckType.BasegameMinor, "Shadows of the Burning Forest", 0, Speed.Slow, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Plant], "Nolan Nasser",
            "If Invaders are present, 2 Fear. If target land is M/J, Push 1 Explorer and 1 Town."),

        // Minors inside color cornered block
        new PowerCard(PowerDeckType.BasegameMinor, "Steam Vents", 1, Speed.Fast, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Fire, Elements.Air, Elements.Water, Elements.Earth], "Joshua Wright",
            "Destroy 1 Explorer. -If you have- 3 Earth: You may instead destroy 1 Town."),
        new PowerCard(PowerDeckType.BasegameMinor, "Veil the Night's Hunt", 1, Speed.Fast, new Ranges(Source.Presence, 2), TargetProperty.Dahan,
            [Elements.Moon, Elements.Air, Elements.Animal], "Loic Belliau",
            "Each Dahan deals 1 Damage to a different Invader. -or- Push up to 3 Dahan."),
        new PowerCard(PowerDeckType.BasegameMinor, "Elemental Boon", 1, Speed.Fast, null, TargetSpirit.Any,
            [], "Moro Rogers",
            "Target Spirit gains 3 different Elements of their choice. If you target another Spirit, you also gain the chosen Elements."),

        // Second Badge
        // Minors
        new PowerCard(PowerDeckType.BasegameMinor, "Devouring Ants", 1, Speed.Slow, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Sun, Elements.Earth, Elements.Animal], "Nolan Nasser",
            "1 Fear. 1 Damage. Destroy 1 Dahan. If target land is J/S, +1 Damage."),
        new PowerCard(PowerDeckType.BasegameMinor, "Dark and Tangled Woods", 1, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Moon, Elements.Earth, Elements.Plant], "Nolan Nasser",
            "2 Fear. If target and is M/J, Defend 3."),
        new PowerCard(PowerDeckType.BasegameMinor, "Sap the Strength of Multitudes", 0, Speed.Fast, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Water, Elements.Animal], "Loic Belliau",
            "Defend 5. -If you have- 1 Air: Increase this Power's Range by 1"),
        new PowerCard(PowerDeckType.BasegameMinor, "Drift down into Slumber", 0, Speed.Fast, new Ranges(Source.Presence, 2), LandAny,
            [Elements.Air, Elements.Earth, Elements.Plant], "Lucas Durham",
            "Defend 1. If target land is J/S, instead, Defend 4."),
        new PowerCard(PowerDeckType.BasegameMinor, "Land of Haunts and Embers", 0, Speed.Fast, new Ranges(Source.Presence, 2), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Air], "Jorge Ramos",
            "2 Fear. Push up to 2 Explorer / Town. If target land has Blight, +2 Fear. Push up to 2 more Explorer / Town. Add 1 Blight."),
        new PowerCard(PowerDeckType.BasegameMinor, "Nature's Resilience", 1, Speed.Fast, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Earth, Elements.Plant, Elements.Animal], "Joshua Wright",
            "Defend 6. -If you have- 2 Water: You may instead remove 1 Blight."),
        new PowerCard(PowerDeckType.BasegameMinor, "Visions of Fiery Doom", 1, Speed.Fast, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Moon, Elements.Fire], "Lucas Durham",
            "1 Fear. Push 1 Explorer / Town. -If you have- 2 Fire: +1 Fear."),
        new PowerCard(PowerDeckType.BasegameMinor, "Pull Beneath the Hungry Earth", 1, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Moon, Elements.Water, Elements.Earth], "Nolan Nasser",
            "If target land has your Presence, 1 Fear and 1 Damage. If target land is S/W, 1 Damage."),
        new PowerCard(PowerDeckType.BasegameMinor, "Call of the Dahan Ways", 1, Speed.Slow, new Ranges(Source.Presence, 1), TargetProperty.Dahan,
            [Elements.Moon, Elements.Water, Elements.Animal], "Loic Belliau",
            "Replace 1 Explorer with 1 Dahan. -If you have- 2 Moon: You may instead replace 1 Town with 1 Dahan."),
        new PowerCard(PowerDeckType.BasegameMinor, "Call to Bloodshed", 1, Speed.Slow, new Ranges(Source.Presence, 1), TargetProperty.Dahan,
            [Elements.Sun, Elements.Fire, Elements.Animal], "Jorge Ramos",
            "1 Damager per Dahan. -or- Gather up to 3 Dahan."),
        new PowerCard(PowerDeckType.BasegameMinor, "Call to Isolation", 0, Speed.Fast, new Ranges(Source.Presence, 1), TargetProperty.Dahan,
            [Elements.Sun, Elements.Air, Elements.Animal], "Graham Stermberg",
            "Push 1 Explorer / Town per Dahan. -or- Push 1 Dahan."),
        new PowerCard(PowerDeckType.BasegameMinor, "Call to Migrate", 1, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Fire, Elements.Air, Elements.Animal], "Graham Stermberg",
            "Gather up to 3 Dahan. Push up to 3 Dahan."),
        new PowerCard(PowerDeckType.BasegameMinor, "Call to Tend", 1, Speed.Slow, new Ranges(Source.Presence, 1), TargetProperty.Dahan,
            [Elements.Water, Elements.Plant, Elements.Animal], "Loic Belliau",
            "Remove 1 Blight. -or- Push up to 3 Dahan."),
        new PowerCard(PowerDeckType.BasegameMinor, "Quicken the Earth's Struggles", 1, Speed.Fast, new Ranges(Source.SacredSite, 0), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Earth, Elements.Animal], "Lucas Durham",
            "1 Damage to each Town / City. -or- Defend 10."),
        new PowerCard(PowerDeckType.BasegameMinor, "Delusions of Danger", 1, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Sun, Elements.Moon, Elements.Air], "Moro Rogers",
            "Push 1 Explorer. -or- 2 Fear."),
        new PowerCard(PowerDeckType.BasegameMinor, "Drought", 1, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Sun, Elements.Fire, Elements.Earth], "Nolan Nasser",
            "Destroy 3 Town. 1 Damage to each Town / City. Add 1 Blight. -If you have- 3 Sun: Destroy 1 City."),
        new PowerCard(PowerDeckType.BasegameMinor, "Gift of Constancy", 0, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Earth], "Moro Rogers",
            "Target Spirit gains 2 Energy. At end of turn, target Spirit may Reclaim 1 Power Card instead of discarding it. If you target another Spirit, you mal also Reclaim 1 Power Card instead of discarding it."),
        new PowerCard(PowerDeckType.BasegameMinor, "Enticing Splendor", 0, Speed.Fast, new Ranges(Source.Presence, 0), TargetProperty.NoBlight,
            [Elements.Sun, Elements.Air, Elements.Plant], "Joshua Wright",
            "Gather 1 Explorer / Town. -or- Gather up to 2 Dahan."),
        new PowerCard(PowerDeckType.BasegameMinor, "Entrancing Apparitions", 1, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Moon, Elements.Air, Elements.Water], "Moro Rogers",
            "Defend 2. If no Invaders are present, gather up to 2 Explorer."),
        new PowerCard(PowerDeckType.BasegameMinor, "Gift of Living Energy", 0, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Fire, Elements.Plant], "Nolan Nasser",
            "Target Spirit gains 1 Energy, +1 Energy if target Spirit is not yourself. If you have at least 2 SacredSite, target Spirit gains +1 Energy."),
        new PowerCard(PowerDeckType.BasegameMinor, "Gift of Power", 0, Speed.Slow, null, TargetSpirit.Any,
            [Elements.Moon, Elements.Water, Elements.Earth, Elements.Plant], "Joshua Wright",
            "Target Spirit gains a Minor Power."),
        new PowerCard(PowerDeckType.BasegameMinor, "Gnawing Rootbiters", 0, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Earth, Elements.Animal], "Moro Rogers",
            "Push up to 2 Town."),
        new PowerCard(PowerDeckType.BasegameMinor, "Lure of the Unknown", 0, Speed.Fast, new Ranges(Source.Presence, 2), TargetProperty.NoInvaders,
            [Elements.Moon, Elements.Fire, Elements.Air, Elements.Plant], "Lucas Durham",
            "Gather 1 Explorer / Town"),
        new PowerCard(PowerDeckType.BasegameMinor, "Purifying Flame", 1, Speed.Slow, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Sun, Elements.Fire, Elements.Air, Elements.Plant], "Jorge Ramos",
            "1 Damage per Blight. If target land is M/S, you may instead remove 1 Blight."),
        new PowerCard(PowerDeckType.BasegameMinor, "Rain of Blood", 0, Speed.Slow, new Ranges(Source.SacredSite, 1), TargetProperty.Invaders,
            [Elements.Air, Elements.Water, Elements.Animal], "Kat Birmelin",
            "2 Fear. If target land has at least 2 Town / City, +1 Fear."),
        new PowerCard(PowerDeckType.BasegameMinor, "Reaching Grasp", 0, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Air, Elements.Water], "Nolan Nasser",
            "Target Spirit gets +2 Range with all their Powers."),
        // Majors
        new PowerCard(PowerDeckType.BasegameMajor, "Accelerated Rot", 4, Speed.Slow, new Ranges(Source.Presence, 2), [Land.Jungle, Land.Wetland],
            [Elements.Sun, Elements.Water, Elements.Plant], "Graham Stermberg",
            "2 Fear. 4 Damage. -If you have- 3 Sun, 2 Water, 3 Plant: +5 Damage. Remove 1 Blight."),
        new PowerCard(PowerDeckType.BasegameMajor, "Cleansing Floods", 5, Speed.Slow, new Ranges(Source.Presence, 1, [Land.Wetland]), LandAny,
            [Elements.Sun, Elements.Water], "Nolan Nasser",
            "4 Damage. Remove 1 Blight. -If you have- 4 Water: +10 Damage."),
        new PowerCard(PowerDeckType.BasegameMajor, "Pillar of Living Flame", 5, Speed.Slow, new Ranges(Source.SacredSite, 2), LandAny,
            [Elements.Fire], "Jorge Ramos",
            "3 Fear. 5 Damage. If target land is J/W, add 1 Blight. -If you have- 4 Fire: +2 Fear and +5 Damage."),
        new PowerCard(PowerDeckType.BasegameMajor, "Poisoned Land", 3, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Earth, Elements.Plant, Elements.Animal], "Nolan Nasser",
            "1 Fear. 7 Damage. Add 1 Blight and destroy all Dahan. -If you have- 3 Earth, 2 Plant, 2 Animal: Per Blight, +1 Fear and +4 Damage."),
        new PowerCard(PowerDeckType.BasegameMajor, "Terrifying Nightmares", 4, Speed.Fast, new Ranges(Source.Presence, 2), LandAny,
            [Elements.Moon, Elements.Air], "Loic Belliau",
            "2 Fear. Push up to 4 Explorer / Town. -If you have- 4 Moon: +4 Fear."),
        new PowerCard(PowerDeckType.BasegameMajor, "The Trees and Stones Speak of War", 2, Speed.Fast, new Ranges(Source.Presence, 1), TargetProperty.Dahan,
            [Elements.Sun, Elements.Earth, Elements.Plant], "Graham Stermberg",
            "1 Damage and Defend 2 per Dahan in target land. -If you have- 2 Sun, 2 Earth, 2 Plant: You may Push up to 2 Dahan, moving the Defend effect with them"),
        new PowerCard(PowerDeckType.BasegameMajor, "Entwined Power", 2, Speed.Fast, null, TargetSpirit.Another,
            [Elements.Moon, Elements.Water, Elements.Plant], "Joshua Wright",
            "You and target Spirit may use each other's Presence to target Powers. Target Spirit gains a Power Card. You take one of the power Cards they did not keep. -If you have- 2 Water, 4 Plant: You and target Spirit each gain 3 Energy and may gift each other 1 Power from hand."),
        new PowerCard(PowerDeckType.BasegameMajor, "Paralyzing Fright", 4, Speed.Fast, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Air, Elements.Earth], "Joshua Wright",
            "4 Fear. Invaders skip all Actions in target land this turn. -If you have- 2 Air, 3 Earth: +4 Fear."),
        new PowerCard(PowerDeckType.BasegameMajor, "Powerstorm", 3, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Fire, Elements.Air], "Nolan Nasser",
            "Target Spirit gains 3 Energy. Once this turn, target may Repeat a Power Card by paying its cost again. -If you have- 2 Sun, 2 Fire, 3 Air: Target may repeat up to 3 total Power Cards by paying their costs."),
        new PowerCard(PowerDeckType.BasegameMajor, "Talons of Lightning", 6, Speed.Fast, new Ranges(Source.Presence, 1), [Land.Mountain, Land.Wetland],
            [Elements.Fire, Elements.Air], "Nolan Nasser",
            "3 Fear. 5 Damage. -If you have- 3 Fire, 3 Air: Destroy 1 Town in each adjacent land. Increase this power's Range to 3 Range."),
        new PowerCard(PowerDeckType.BasegameMajor, "The Jungle Hungers", 3, Speed.Slow, new Ranges(Source.Presence, 1, [Land.Jungle]), LandAny,
            [Elements.Moon, Elements.Plant], "Joshua Wright",
            "Destroy all Explorer and all Town. Destroy all Dahan. -If you have- 2 Moon, 3 Plant: Destroy 1 City. Do not destroy any Dahan."),
        new PowerCard(PowerDeckType.BasegameMajor, "The land Thrashes in Furious Pain", 4, Speed.Slow, new Ranges(Source.Presence, 2), TargetProperty.Blight,
            [Elements.Moon, Elements.Fire, Elements.Earth], "Nolan Nasser",
            "2 Damage per Blight in target land. +1 Damage per Blight in adjacent lands. -If you have- 3 Moon, 3 Earth: Repeat on an adjacent land."),
        new PowerCard(PowerDeckType.BasegameMajor, "Tsunami", 6, Speed.Slow, new Ranges(Source.SacredSite, 2), Land.Coastal,
            [Elements.Water, Elements.Earth], "Jason Behnke",
            "2 Fear. 8 Damage. Destroy 2 Dahan. -If you have- 3 Water, 2 Earth: +1 Fear, 4 Damage and Destroy 1 Dahan in each other Coastal land on the same board."),
        new PowerCard(PowerDeckType.BasegameMajor, "Vigor of the Breaking Dawn", 3, Speed.Fast, new Ranges(Source.Presence, 2), TargetProperty.Dahan,
            [Elements.Sun, Elements.Animal], "Loic Belliau",
            "2 Damage per Dahan in target land. -If you have- 3 Sun, 2 Animal: You may Push up to 2 Dahan. In lands you Pushed Dahan to, 2 Damage per Dahan."),
        new PowerCard(PowerDeckType.BasegameMajor, "Vengeance of the Dead", 3, Speed.Fast, new Ranges(Source.Presence, 3), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Animal], "Kat Birmelin",
            "3 Fear. During the rest of this turn, 1 Damage in target land for each Town / City / Dahan destroyed there. -If you have- 3 Animal: Damage from this Power may be dealt into adjacent lands."),
        new PowerCard(PowerDeckType.BasegameMajor, "Wrap in Wings of Sunlight", 3, Speed.Fast, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Sun, Elements.Air, Elements.Animal], "Loic Belliau",
            "Move up to 5 Dahan from target land to any land. Defend 5 in that land. -If you have- 2 Sun, 2 Air, 2 Animal: First, Gather up to 3 Dahan."),
        new PowerCard(PowerDeckType.BasegameMajor, "Blazing Renewal", 5, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Fire, Elements.Earth, Elements.Plant], "Nolan Nasser",
            "Target Spirit places 2 of their destroyed Presence into a single land, up to 2 Range from your Presence. If any Presence was returned, 2 damage to each Town / City in that land. -If you have- 3 Fire, 3 Earth, 2 Plant: 4 Damage."),
        new PowerCard(PowerDeckType.BasegameMajor, "Winds of Rust and Atrophy", 3, Speed.Fast, new Ranges(Source.SacredSite, 3), LandAny,
            [Elements.Air, Elements.Water, Elements.Animal], "Joshua Wright",
            "1 Fear and Defend 6. Replace 1 City with 1 Town or 1 Town with 1 Explorer. -If you have- 3 Air, 3 Water, 2 Animal: Repeat this Power."),
        new PowerCard(PowerDeckType.BasegameMajor, "Indomitable Claim", 4, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Sun, Elements.Earth], "Jorge Ramos",
            "Add 1 Presence in target land even if you normally could not due to land type. Defend 20. -If you have- 2 Sun, 3 Earth: 3 Fear if Invaders are present. Invaders skip all Actions in target land this turn."),
        new PowerCard(PowerDeckType.BasegameMajor, "Mists of Oblivion", 4, Speed.Slow, new Ranges(Source.Presence, 3), LandAny,
            [Elements.Moon, Elements.Air, Elements.Water], "Nolan Nasser",
            "1 Damage to each Invader in target land. 1 Fear per Town / City destroyed by this Power, to a maximum of 4. -If you have- 2 Moon, 3 Air, 2 Water: +3 Damage."),
        new PowerCard(PowerDeckType.BasegameMajor, "Infinite Vitality", 3, Speed.Fast, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Earth, Elements.Plant, Elements.Animal], "Joshua Wright",
            "Dahan have +4 Health while in target land. Whenever Blight would be added to target land, instead leave it on the card. -If you have- 4 Earth: Dahan ignore Damage and Destruction effects. Remove 1 Blight from target or adjacent land."),
        new PowerCard(PowerDeckType.BasegameMajor, "Dissolve the bonds", 4, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Fire, Elements.Water, Elements.Animal], "Jorge Ramos",
            "Replace 1 City with 2 Explorer. Replace 1 Town with 1 Explorer. Replace 1 Dahan with 1 Explorer. Push all Explorer from target land to as many different lands as possible. -If you have- 2 Fire, 2 Water, 3 Animal: Before Pushing, Explorer and Town / City do Damage to each other."),

        // Expansion
        // Majors
        new PowerCard(PowerDeckType.ExpansionMajor, "Strangling Firevine", 4, Speed.Slow, new Ranges(Source.Presence, 1, [Land.Sand]), LandAny,
            [Elements.Fire, Elements.Plant], "Nolan Nasser",
            "Destroy all Explorer. Add 1 Wilds. Add 1 Wilds in the originating Sands. 1 Damage per Wilds in / adjacent to target land. -If you have- 2 Fire, 3 Plant: +1 Damage per Wilds in / adjacent to target land."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Bloodwrap Plague", 4, Speed.Fast, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Water, Elements.Earth, Elements.Animal], "Jorge Ramos",
            "Add 2 Disease. For each Disease in target land, Defend 1 in target and all adjacent lands. -If you have- 2 Earth, 4 Animal: 2 Fear. For each Disease in target land do 1 Damage in target or an adjacent land."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Cast down into the Briny Deep", 9, Speed.Slow, new Ranges(Source.SacredSite, 1), [Land.Coastal],
            [Elements.Sun, Elements.Moon, Elements.Water, Elements.Earth], "Jason Behnke",
            "6 Fear. Destroy all Invaders. -If you have- 2 Sun, 2 Moon, 4 Water, 4 Earth: Destroy the board containing target land and everything on that board. All destroyed Blight is removed from the game instead of being returned to the Blight Card."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Death Falls Gently from Open Blossoms", 4, Speed.Slow, new Ranges(Source.Presence, 3), [Land.Jungle, Land.Sand],
            [Elements.Moon, Elements.Air, Elements.Plant], "Graham Stermberg",
            "4 Damage. If any Invaders remain, add 1 Disease. -If you have- 3 Air, 3 Plant: 3 Fear. Add 1 Disease to 2 adjacent lands with Invaders."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Fire and Flood", 7, Speed.Slow, new Ranges(Source.SacredSite, [1, 2]), LandAny,
            [Elements.Sun, Elements.Fire, Elements.Water], "Jason Behnke",
            "4 Damage in each target land. (Range must be measured from the same SacredSite.) -If you have- 3 Fire: +4 Damage in either target land. 3 Water: +4 Damage in either target land."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Grant Hatred a Ravenous Form", 4, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Moon, Elements.Fire], "Nolan Nasser",
            "For each Strife / Blight in target land, 1 Fear and 2 Damage. If this destroys all invaders in target land, add 1 Beasts. -If you have- 4 Moon, 2 Fire: Add 1 Strife in up to 3 adjacent lands."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Insatiable Hinger of the Swarm", 4, Speed.Fast, new Ranges(Source.SacredSite, 2), LandAny,
            [Elements.Air, Elements.Plant, Elements.Animal], "Lucas Durham",
            "Add 1 Blight. Add 2 Beasts. Gather up to 2 Beasts. Each Beasts does 1 Fear, 2 Damage to Invaders and 2 Damage to Dahan. Destroy 1 Beasts. -If you have- 2 Air, 4 Animal: Repeat this Power on an adjacent land."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Instruments of their own Ruin", 4, Speed.Fast, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Sun, Elements.Fire, Elements.Air, Elements.Animal], "Lucas Durham",
            "Add 1 Strife. Each Invader with Strife deals Damage to other Invaders in target land. -If you have- 4 Sun, 2 Fire, 2 Animal: Instead, if Invaders Ravage in target land, they damage Invaders in adjacent lands instead of Dahan and the land. Dahan in target land do not fight back."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Flow like Water, Reach like Air", 2, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Air, Elements.Water], "Joshua Wright",
            "Target Spirit gets +2 Range with all Powers. Target Spirit may Push 1 of their Presence to an adjacent land, bringing up to 2 Explorer, 2 Town and 2 Dahan along with it. -If you have- 2 Air, 2 Water: The moved Presence may also bring along up to 2 City and up to 2 Blight."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Pent-Up Calamity", 3, Speed.Fast, new Ranges(Source.Presence, 2), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Earth, Elements.Plant, Elements.Animal], "Joshua Wright",
            "Add 1 Disease and 1 Strife. -or- Remove any number of Beasts / Disease / Strife / Wilds. For each token removed, 1 Fear and 3 Damage. -If you have- 2 Moon, 3 Fire: If you have removed tokens, return up to 2 of them. Otherwise, add 2 Strife."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Pyroclastic Flow", 3, Speed.Fast, new Ranges(Source.Presence, 1, [Land.Mountain]), LandAny,
            [Elements.Fire, Elements.Air, Elements.Earth], "Joshua Wright",
            "2 Damage. Destroy all Explorer. If target land is J/W, add 1 Blight. -If you have- 3 Air, 2 Fire, 2 Earth: +4 Damage. Add 1 Wilds."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Savage Transformation", 2, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Moon, Elements.Animal], "Loic Belliau",
            "2 Fear. Replace 1 Explorer with 1 Beasts. -If you have- 3 Animal, 2 Moon: Replace 1 additional Explorer with 1 Beasts in either target or adjacent land."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Sea Monsters", 5, Speed.Slow, new Ranges(Source.Presence, 1), [Land.Coastal, Land.Wetland],
            [Elements.Water, Elements.Animal], "Moro Rogers",
            "Add 1 Beasts. Per Beasts, 2 Fear and 3 Damage. Per Blight, 1 Damage. -If you have- 3 Water, 3 Animal: Repeat this power."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Tigers Hunting", 2, Speed.Fast, new Ranges(Source.Presence, 1, [Land.Jungle]), TargetProperty.NoBlight,
            [Elements.Sun, Elements.Moon, Elements.Animal], "Cari Corene",
            "2 Fear. Add 1 Beasts. Gather up to 1 Beasts. 1 Damage per Beasts. Push up to 2 Beasts. -If you have- 2 Sun, 2 Moon, 3 Animal: 1 Damage in an adjacent land without Blight, and +1 Damage per Beasts there."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Unrelenting Growth", 4, Speed.Slow, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Fire, Elements.Water, Elements.Plant], "Joshua Wright",
            "Target Spirit adds 2 Presence and 1 Wilds to a land at 1 Range. -If you have- 3 Sun, 3 Plant: In that land, add 1 additional Wilds and remove 1 Blight. Target Spirit gains a Power Card."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Volcanic Eruption", 8, Speed.Slow, new Ranges(Source.Presence, 1, [Land.Mountain]), LandAny,
            [Elements.Fire, Elements.Earth], "Nolan Nasser",
            "6 Fear. 20 Damage. Destroy all Dahan and Beasts. Add 1 Blight. -If you have- 4 Fire, 3 Earth: Destroy all Invaders. Add 1 Wilds. In each adjacent land: 10 Damage. Destroy all Dahan and Beasts. If there are no Blight, add 1 Blight."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Sweep into the Sea", 4, Speed.Slow, new Ranges(Source.Presence, 2), LandAny,
            [Elements.Sun, Elements.Air, Elements.Water], "Joshua Wright",
            "Push all Explorer and Town one land towards the nearest Ocean. -or- If target land is Coastal, destroy all Explorer and Town. -If you have- 3 Sun, 2 Water: Repeat on an adjacent land."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Manifest Incarnation", 6, Speed.Slow, new Ranges(Source.Presence, 0), TargetProperty.City,
            [Elements.Sun, Elements.Moon, Elements.Earth, Elements.Animal], "Moro Rogers",
            "6 Fear. +1 Fear for each Town / City and for each of your Presence in target land. Remove 1 City, 1 Town and 1 Explorer. Then Invaders in target land Ravage. -If you have- 3 Sun, 3 Moon: +3 Fear. Invaders do -6 Damage on their Ravage."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Smothering Infestation", 3, Speed.Slow, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Water, Elements.Plant], "Joshua Wright",
            "Add 1 Disease. If target land is J/W, 2 Fear and 3 Damage. -If you have- 2 Plant, 2 Water: 1 Damage to each Invader."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Twisted Flowers Murmur Ultimatums", 5, Speed.Slow, new Ranges(Source.SacredSite, 1), TargetProperty.Invaders,
            [Elements.Sun, Elements.Moon, Elements.Air, Elements.Earth, Elements.Plant], "Kat Birmelin",
            "4 Fear. Add 1 Strife. If the Terror Level is 2 or higher, remove 2 Invaders. -If you have- 3 Moon, 2 Air, 3 Plant: +3 Fear, before the Terror Level check. 3 Damage."),
        new PowerCard(PowerDeckType.ExpansionMajor, "Unlock the Gates of Deepest Power", 4, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Moon, Elements.Fire, Elements.Air, Elements.Water, Elements.Earth, Elements.Plant, Elements.Animal], "Joshua Wright",
            "Target Spirit gains a Major Power by drawing 2 and keeping 1, without having to Forget another Power Card. -If you have- 2 Sun, 2 Moon, 2 Fire, 2 Air, 2 Water, 2 Earth, 2 Plant, 2 Animal: Target Spirit may now play the Major Power they keep by paying half its cost (round up) OR by Forgetting it at the end of turn. It gains all elemental thresholds."),

        // Minor
        new PowerCard(PowerDeckType.ExpansionMinor, "Inflame the Fires of Life", 1, Speed.Slow, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Plant, Elements.Animal], "Kat Birmelin",
            "Add 1 Disease. -or'- 1 Fear. Add 1 Strife. -If you have- 3 Animal: You may do both."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Fire in the Sky", 1, Speed.Fast, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Sun, Elements.Fire, Elements.Air], "Moro Rogers",
            "2 Fear. Add 1 Strife"),
        new PowerCard(PowerDeckType.ExpansionMinor, "Fleshrot Fever", 1, Speed.Slow, new Ranges(Source.Presence, 1), [Land.Jungle, Land.Sand],
            [Elements.Fire, Elements.Air, Elements.Water, Elements.Animal], "Joshua Wright",
            "1 Fear. Add 1 Disease."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Gold's Allure", 0, Speed.Slow, new Ranges(Source.Presence, 1), [Land.Mountain],
            [Elements.Fire, Elements.Earth, Elements.Animal], "Lucas Durham",
            "Gather 1 Explorer. and 1 Town. Add 1 Strife."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Guardian Serpents", 1, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Moon, Elements.Earth, Elements.Animal], "Moro Rogers",
            "Add 1 Beasts in one of target Spirit's lands. If target Spirit has a SacredSite in that land: Defend 4 there."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Here there be Monsters", 0, Speed.Slow, new Ranges(Source.Presence, 0), Land.Inland,
            [Elements.Moon, Elements.Air, Elements.Animal], "Joshua Wright",
            "You may Push 1 Explorer / Town / Dahan. 2 Fear. If target land has any Beasts, 1 Fear."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Infested Aquifers", 1, Speed.Slow, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Moon, Elements.Water, Elements.Earth, Elements.Animal], "Nolan Nasser",
            "If target land has any Disease, 1 Damage to each Invader there. -or- If target land is M/W, 1 Fear and add 1 Disease."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Poisoned Dew", 1, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Fire, Elements.Water, Elements.Plant], "Cari Corene",
            "Destroy 1 Explorer. If target land is J/W, destroy all Explorer."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Portents of Disaster", 0, Speed.Fast, new Ranges(Source.SacredSite, 1), TargetProperty.Invaders,
            [Elements.Sun, Elements.Moon, Elements.Air], "Nolan Nasser",
            "2 Fear. The next time an Invader is destroyed in target land this turn, 1 Fear."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Prowling Panthers", 1, Speed.Slow, new Ranges(Source.Presence, 1), [Land.Mountain, Land.Jungle],
            [Elements.Moon, Elements.Fire   , Elements.Animal], "Moro Rogers",
            "1 Fear. Add 1 Beasts. -or- If target land has Beasts, destroy 1 Explorer / Town."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Renewing Rain", 1, Speed.Slow , new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Water, Elements.Earth, Elements.Plant], "Nolan Nasser",
            "If target land is J/S, remove 1 Blight. -If you have- 3 Plant: Add 1 Wilds."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Rites of the Land's Rejection", 1, Speed.Fast, new Ranges(Source.SacredSite, 2), TargetProperty.Dahan,
            [Elements.Moon, Elements.Fire, Elements.Earth], "Joshua Wright",
            "Invaders do not Build in target land this turn. 1 Fear per Town / City or 1 Fear per Dahan, whichever is less. -or- Push up to 3 Dahan from target land."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Pact of the Joined Hunt", 1, Speed.Slow, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Plant, Elements.Animal], "Jorge Ramos",
            "Target Spirit Gathers 1 Dahan into one of their lands. 1 Damage in that land per Dahan present."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Razor-Sharp Undergrowth", 1, Speed.Fast, new Ranges(Source.Presence, 0), TargetProperty.NoBlight,
            [Elements.Moon, Elements.Plant], "Cari Corene",
            "Destroy 1 Explorer and 1 Dahan. Add 1 Wilds. Defend 2."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Growth through Sacrifice", 0, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Moon, Elements.Fire, Elements.Water, Elements.Plant], "Lucas Durham",
            "Destroy 1 of your Presence. Target Spirit removes 1 Blight from one of their lands. -or- Adds 1 Presence to one of their lands. -If you have- 2 Sun: They may do both, in the same land."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Scour the Land", 1, Speed.Slow, new Ranges(Source.SacredSite, 2), LandAny,
            [Elements.Air, Elements.Earth], "Joshua Wright",
            "Destroy 3 Town and all Explorer. Add 1 Blight. -If you have- 3 Air: This power may be Fast."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Sky stretches to Shore", 1, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Air, Elements.Water, Elements.Earth], "Joshua Wright",
            "This turn, target Spirit may use 1 Slow Power as if it were Fast, or vice versa. Target Spirit gains +3 Range for targeting Coast lands only."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Swarming Wasps", 0, Speed.Fast, new Ranges(Source.Presence, 1), TargetProperty.NoBlight,
            [Elements.Fire, Elements.Air, Elements.Animal], "Joshua Wright",
            "Add 1 Beasts. -or- If target land has Beasts, Push up to 2 Explorer."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Absorb Corruption", 1, Speed.Slow, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Sun, Elements.Earth, Elements.Plant], "Nolan Nasser",
            "Gather 1 Blight. -or- Pay 1 Energy to remove 1 Blight. -If you have- 2 Plant: You may do both."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Animated Wrackroot", 0, Speed.Slow, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Plant], "Joshua Wright",
            "1 Fear. Destroy 1 Explorer. -or- Add 1 Wilds."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Promises of Protection", 0, Speed.Fast, new Ranges(Source.SacredSite, 2), LandAny,
            [Elements.Sun, Elements.Earth, Elements.Animal], "Lucas Durham",
            "Gather up to 2 Dahan. Dahan have +2 Health while in target land."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Call to Ferocity", 0, Speed.Slow, new Ranges(Source.Presence, 1), TargetProperty.Invaders,
            [Elements.Sun, Elements.Fire, Elements.Earth], "Joshua Wright",
            "Gather up to 3 Dahan. -or- If target land has Dahan, 1 Fear and Push 1 Explorer and 1 Town."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Call to Trade", 1, Speed.Fast, new Ranges(Source.Presence, 2), TargetProperty.Dahan,
            [Elements.Air, Elements.Water, Elements.Earth, Elements.Plant], "Kat Birmelin",
            "You may Gather 1 Dahan. If the Terror Level is 2 or lower, Gather 1 Town and the first Ravage in target land this turn becomes a Build there instead."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Confounding Mists", 1, Speed.Fast, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Air, Elements.Water], "Loic Belliau",
            "Defend 4. -or- Each Invader added to target land this turn may be immediately Pushed to any adjacent land."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Cycles of Time and Tide", 1, Speed.Fast, new Ranges(Source.Presence, 1), [Land.Coastal],
            [Elements.Sun, Elements.Moon, Elements.Water], "Joshua Wright",
            "If there are Dahan, add 1 Dahan. If there are no Dahan, remove 1 Blight."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Disorienting Landscape", 1, Speed.Fast, new Ranges(Source.SacredSite, 2), LandAny,
            [Elements.Moon, Elements.Air, Elements.Plant], "Nolan Nasser",
            "Push 1 Explorer. If target land is M/J, add 1 Wilds."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Elusive Ambushes", 1, Speed.Fast, new Ranges(Source.Presence, 1), TargetProperty.Dahan,
            [Elements.Sun, Elements.Fire, Elements.Water], "Nolan Nasser",
            "1 Damage. -or- Defend 4."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Tormenting Rotflies", 1, Speed.Slow, new Ranges(Source.Presence, 2), [Land.Sand, Land.Wetland],
            [Elements.Air, Elements.Plant, Elements.Animal], "Kat Birmelin",
            "Add 1 Disease. -or- If target land has Invaders, 2 Fear. If Disease is present, +1 Fear. If Blight is present, +1 Fear."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Twilight Fog brings Madness", 0, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Sun, Elements.Moon, Elements.Air, Elements.Water], "Loic Belliau",
            "Add 1 Strife. Push 1 Dahan. Each remaining Dahan takes 1 Damage."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Teeming Rivers", 1, Speed.Slow, new Ranges(Source.SacredSite, 2), [Land.Mountain, Land.Wetland],
            [Elements.Sun, Elements.Water, Elements.Plant, Elements.Animal], "Lucas Durham",
            "If target land has no Blight, add 1 Beasts. If target land has exactly 1 Blight, remove it."),
        new PowerCard(PowerDeckType.ExpansionMinor, "Spur on with Words of Fire", 1, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Fire, Elements.Air], "Nolan Nasser",
            "If you target a Spirit other than yourself, they gain +1 Energy. Target Spirit may immediately play another Power Card by paying its cost. (If it is Slow, it does not resolve until later.)"),

        // Spirit Cards
        new PowerCard(Unique.SharpFangsBehindTheLeaves, "Prey on the Builders", 1, Speed.Fast, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Moon, Elements.Fire, Elements.Animal], "Moro Rogers",
            "You may Gather 1 Beasts. If target land has Beasts, Invaders do not Build there this turn."),
        new PowerCard(Unique.SharpFangsBehindTheLeaves, "Teeth Gleam from Darkness", 1, Speed.Slow, new Ranges(Source.Presence, 1, [Land.Jungle]), TargetProperty.NoBlight,
            [Elements.Moon, Elements.Plant, Elements.Animal], "Moro Rogers",
            "1 Fear. Add 1 Beasts. -or- If target land has both Beasts and Invaders: 3 Fear."),
        new PowerCard(Unique.SharpFangsBehindTheLeaves, "Too near the Jungle", 0, Speed.Slow, new Ranges(Source.Presence, 1, [Land.Jungle]), LandAny,
            [Elements.Plant, Elements.Animal], "Moro Rogers",
            "1 Fear. Destroy 1 Explorer."),
        new PowerCard(Unique.SharpFangsBehindTheLeaves, "Terrifying Chase", 1, Speed.Slow, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Sun, Elements.Animal], "Moro Rogers",
            "Push 2 Explorer / Town / Dahan. Push another 2 Explorer / Town / Dahan per Beasts in target land. If you Pushed any Invaders, 2 Fear."),
        new PowerCard(Unique.KeeperOfTheForbiddenWilds, "Towering Wrath", 3, Speed.Slow, new Ranges(Source.SacredSite, 1), LandAny,
            [Elements.Sun, Elements.Fire, Elements.Plant], "Joshua Wright",
            "2 Fear. 2 Damage per your SacredSite in or adjacent to target land. Destroy all Dahan."),
        new PowerCard(Unique.KeeperOfTheForbiddenWilds, "Regrow from Roots", 1, Speed.Slow, new Ranges(Source.Presence, 1), [Land.Jungle, Land.Wetland],
            [Elements.Water, Elements.Earth, Elements.Plant], "Joshua Wright",
            "If there are 2 Blight or fewer in target land, remove 1 Blight."),
        new PowerCard(Unique.KeeperOfTheForbiddenWilds, "Boon of Growing Power", 1, Speed.Slow, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Moon, Elements.Plant], "Joshua Wright",
            "Target Spirit gains a Power Card. If you target another Spirit, they also gain 1 Energy."),
        new PowerCard(Unique.KeeperOfTheForbiddenWilds, "Sacrosanct Wilderness", 2, Speed.Fast, new Ranges(Source.Presence, 1), TargetProperty.NoBlight,
            [Elements.Sun, Elements.Earth, Elements.Plant], "Joshua Wright",
            "Push 2 Dahan. 2 Damage per Wilds in target land. -or- Add 1 Wilds."),

        // Promo
        // Uniques
        new PowerCard(Unique.HeartOfTheWildfire, "Flash-Fires", 2, Speed.Slow, new Ranges(Source.Presence, 1), LandAny,
            [Elements.Fire, Elements.Air], "Nolan Nasser",
            "1 Fear. 1 Damage. -If you have- 2 Air: This Power is Fast."),
        new PowerCard(Unique.HeartOfTheWildfire, "Asphyxiating Smoke", 2, Speed.Slow, new Ranges(Source.SacredSite, 2), LandAny,
            [Elements.Fire, Elements.Air, Elements.Plant], "Nolan Nasser",
            "1 Fear. Destroy 1 Town. Push 1 Dahan."),
        new PowerCard(Unique.HeartOfTheWildfire, "Flame's Fury", 0, Speed.Fast, null, TargetSpirit.Any,
            [Elements.Sun, Elements.Fire, Elements.Plant], "Nolan Nasser",
            "Target Spirit gains 1 Energy. Target Spirit does +1 Damage with each Damage dealing Power they use this turn. (Powers which damage multiple lands or each Invader only get 1 extra damage total. Repeated Powers keep the +1 boost. Destroy effects don't get any bonus.)"),
        new PowerCard(Unique.HeartOfTheWildfire, "Threatening Flames", 0, Speed.Fast, new Ranges(Source.Presence, 0), [TargetProperty.Blight, TargetProperty.Invaders],
            [Elements.Fire, Elements.Plant], "Nolan Nasser",
            "2 Fear. Push 1 Explorer / Town per Terror Level from target land to adjacent lands without your Presence. If there are no such adjacent lands, +2 Fear."),
        new PowerCard(Unique.SerpentSlumberingBeneathTheIsland, "Gift of the Primordial Deeps", 1, Speed.Fast, null, TargetSpirit.Another,
            [Elements.Moon, Elements.Earth], "Jorge Ramos",
            "Target Spirit gains a Minor Power. Target Spirit chooses to either: Play it immediately by paying its cost. -or- Gain 1 Moon and 1 Earth."),
        new PowerCard(Unique.SerpentSlumberingBeneathTheIsland, "Gift of Flowing Power", 1, Speed.Fast, null, TargetSpirit.Another,
            [Elements.Fire, Elements.Water], "Jorge Ramos",
            "Target Spirit gains 1 Energy. Target Spirit chooses to either: Play another Power Card by paying its cost. -or- Gain 1 Fire and 1 Water."),
        new PowerCard(Unique.SerpentSlumberingBeneathTheIsland, "Absorb Essence", 2, Speed.Fast, null, TargetSpirit.Another,
            [Elements.Moon, Elements.Fire, Elements.Water, Elements.Earth], "Jorge Ramos",
            "Gain 3 Energy. Move 1 of target Spirit's Presence from the board to your Deep Slumber track. Absorbed Presence cannot be returned to play. Target Spirit gains 1 Any and 1 Energy."),
        new PowerCard(Unique.SerpentSlumberingBeneathTheIsland, "Elemental Aegis", 1, Speed.Fast, new Ranges(Source.Presence, 0), LandAny,
            [Elements.Fire, Elements.Water, Elements.Earth], "Jorge Ramos",
            "Defend 2 in target land and all adjacent lands. For every Presence on your \"Deep Slumber\" track, Defend 1 in target land and all adjacent lands."),

        // Fear Cards
        // Basegame
        new FearCard(FearType.Basegame, "Fear of the Unseen",
            "Each player removes 1 Explorer / Town from a land with SacredSite.",
            "Each player removes 1 Explorer / Town from a land with Presence.",
            "Each player removes 1 Explorer / Town from a land with Presence, or 1 City from a land with SacredSite."),
        new FearCard(FearType.Basegame, "Scapegoats",
            "Each Town destroys 1 Explorer in its land.",
            "Each Town destroys 1 Explorer in its land. Each City destroys 2 Explorer in its land.",
            "Destroy all Explorer in lands with Town / City. Each City destroys 1 Town in its land."),
        new FearCard(FearType.Basegame, "Emigration Accelerates",
            "Each player removes 1 Explorer from a Coastal land.",
            "Each player removes 1 Explorer / Town from a Coastal land.",
            "Each player removes 1 Explorer / Town from any land."),
        new FearCard(FearType.Basegame, "Dahan on their Guard",
            "In each land, Defend 1 per Dahan.",
            "In each land with Dahan, Defend 1, plus an additional Defend 1 per Dahan.",
            "In each land, Defend 2 per Dahan."),
        new FearCard(FearType.Basegame, "Tall Tales of Savagery",
            "Each player removes 1 Explorer from a land with Dahan.",
            "Each player removes 2 Explorer or 1 Town from a land with Dahan.",
            "Remove 2 Explorer or 1 Town from each land with Dahan. Then, remove 1 City from each land with at least 2 Dahan."),
        new FearCard(FearType.Basegame, "Retreat!",
            "Each player may Push up to 2 Explorer from an Inland land.",
            "Each player may Push up to 3 Explorer / Town from an Inland land.",
            "Each player may Push any number of Explorer / Town from one land."),
        new FearCard(FearType.Basegame, "Dahan Raid",
            "Each player chooses a differend land with Dahan. 1 Damage there.",
            "Each player chooses a differend land with Dahan. 1 Damage per Dahan there.",
            "Each player chooses a differend land with Dahan. 2 Damage per Dahan there."),
        new FearCard(FearType.Basegame, "Dahan Enheartened",
            "Each player may Push 1 Dahan from a land with Invaders or Gather 1 Dahan into a land with Invaders.",
            "Eac hplayer chooses a differend land. In chosen lands: Gather up to 2 Dahan, then 1 Damage if Dahan are present.",
            "Each player chooses a differend land. In chosen lands: Gather up to 2 Dahan, then 1 Damage per Dahan present."),
        new FearCard(FearType.Basegame, "Avoid the Dahan",
            "Invaders do not Explore into lands with at least 2 Dahan.",
            "Invaders do not Build in lands where Dahan outnumber Town / City.",
            "Invaders do not Build in lands with Dahan."),
        new FearCard(FearType.Basegame, "Seek Safety",
            "Each player may Push 1 Explorer into a land with more Town / City than the land it came from.",
            "Each player may Gather 1 Explorer into a land with Town / City, or Gather 1 Town into a land with City.",
            "Each player may remove up to 3 Health worth of Invaders from a land without Town."),
        new FearCard(FearType.Basegame, "Wary of the Interior",
            "Each player removes 1 Explorer from an Inland land.",
            "Each player removes 1 Explorer / Town from an Inland land.",
            "Each player removes 1 Explorer / Town from any land."),
        new FearCard(FearType.Basegame, "Belief Takes Root",
            "Defend 2 in all lands with Presence.",
            "Defend 2 in all lands with Presence. Each Spirit gains 1 Energy per SacredSite they have in lands with Invaders.",
            "Each player chooses a differend land and removes up to 2 Health worth of Invaders per Presence there."),
        new FearCard(FearType.Basegame, "Isolation",
            "Each player removes 1 Explorer / Town from a land where it is the only Invader.",
            "Each player removes 1 Explorer / Town from a land with 2 or fewer Invaders.",
            "Each player removes an Invader from a land with 2 or fewer Invaders."),
        new FearCard(FearType.Basegame, "Overseas Trade Seems Safer",
            "Defend 3 in all Coastal lands.",
            "Defend 6 in all Coastal lands. Invaders do not Build City in Coastal lands this turn.",
            "Defend 9 in all Coastal lands. Invaders do not Build in Coastal lands this turn."),
        new FearCard(FearType.Basegame, "Trade Suffers",
            "Invaders do not Build in lands with City.",
            "Each player may replace 1 Town with 1 Explorer in a Coastal land.",
            "Each player may replace 1 City with 1 Town or 1 Town with 1 Explorer in a Coastal land."),
        new FearCard(FearType.Expansion, "Demoralized",
            "Defend 1 in all lands.",
            "Defend 2 in all lands.",
            "Defend 3 in all lands."),
        new FearCard(FearType.Expansion, "Plan for Departure",
            "Each player may Gather 1 Town into a Coastal land.",
            "Each player may Gather 1 Explorer / Town into a Coastal land. Defend 2 in all Coastal lands.",
            "Each player may Gather up to 2 Explorer / Town into a Coastal land. Defend 4 in all Coastal lands."),
        new FearCard(FearType.Expansion, "Tread Carefully",
            "Each player may choose a land with Dahan or adjacent to at least 5 Dahan. Invaders do not Ravage there this turn.",
            "Each player may choose a land with Dahan or adjacent to at least 3 Dahan. Invaders do not Ravage there this turn.",
            "Each player may choose a land with Dahan or adjacent to Dahan. Invaders do not Ravage there this turn."),
        new FearCard(FearType.Expansion, "Dahan Attack",
            "Each player removes 1 Explorer from a land with Dahan.",
            "Each player chooses a different land with Dahan. 1 Damager per Dahan there.",
            "Each player chooses a different land with Town / City. Gather 1 Dahan into that land. Then, 2 Damage per Dahan there."),
        new FearCard(FearType.Expansion, "Explorers are Reluctant",
            "During the next normal Explore, skip the lowest numbered land matching the Invader Card on each board.",
            "Skip the next normal Explore. During the next invader Phase, draw an additional Explore card.",
            "Skip the next normal Explore, but still reveal a card. (Perform the Stage II Escalation if relevant.) Cards shift left as usual."),
        new FearCard(FearType.Expansion, "Immigration Slows",
            "During the next normal Build, skip the lowest-numbered land matching the Invader Card on each board.",
            "Skip the next normal Build. The Build Card remains in place instead of skifting left.",
            "Skip the next normal Build. The Build Card shifts left as usual."),
        new FearCard(FearType.Expansion, "Flee the Pestilent Land",
            "Each player removes 1 Explorer / Town from a land with Disease.",
            "Each player removes up to 3 Health of Invaders from a land with Disease or 1 Explorer from an Inland land.",
            "Each player removes up to 5 Health of Invaders from a land with Disease, or 1 Explorer / Town from an Inland land."),
        new FearCard(FearType.Expansion, "Quarantine",
            "Explore does not affect Coastal lands.",
            "Explore does not affect Coastal lands. Lands with Disease are not a source of Invaders when Exploring.",
            "Explore does not affect Coastal lands. Invaders do not act in lands with Disease."),
        new FearCard(FearType.Expansion, "Too Many Monsters",
            "Each player removes 1 Explorer / Town from a land with Beasts.",
            "Each player removes 1 Explorer and 1 Town from a land with Beasts, or 1 Explorer from a land adjacent to Beasts.",
            "Each player removes 2 Explorer and 2 Town from a land with Beasts or 1 Explorer / Town from a land adjacent to Beasts."),
        new FearCard(FearType.Expansion, "Panicked by Wild Beasts",
            "Each player adds 1 Strife in a land with or adjacent to Beasts.",
            "Each player adds 1 Strife in a land with or adjacent to Beasts. Invaders skip their normal Explore and Build in lands with Beasts.",
            "Each player adds 1 Strife in a land with or adjacent to Beasts. Invaders skip all normal Actions in lands with Beasts."),
        new FearCard(FearType.Expansion, "Depart the Dangerous Land",
            "Each player removes 1 Explorer from a land with Beasts, Disease, or at least 2 Dahan.",
            "Each player removes 1 Explorer / town from a land with Beasts, Disease, or at least 2 Dahan.",
            "Each player removes up to 4 Health worth of Invaders from a land with Beasts, Disease, or at least 2 Dahan."),
        new FearCard(FearType.Expansion, "Unrest",
            "Each player adds 1 Strife to a Town.",
            "Each player adds 1 Strife to a Town. For the rest of this turn, Invaders have -1 Health per Strife to a minimum of 1.",
            "Each player adds 1 Strife to an Invader. For the rest of this turn, Invaders have -1 Health per Strife to a minimum of 1."),
        new FearCard(FearType.Expansion, "Panic",
            "Each player adds 1 Strife in a land with Beasts / Disease / Dahan.",
            "Each player adds 1 Strife in a land with Beasts / Disease / Dahan. For the rest of this turn, Invaders have -1 Health per Strife to a minimum of 1.",
            "Each player adds 1 Strife to an Invader. For the rest of this turn, Invaders have -1 Health per Strife to a minimum of 1."),
        new FearCard(FearType.Expansion, "Discord",
            "Each player adds 1 Strife in a different land with at least 2 Invaders.",
            "Each player adds 1 Strife in a different land with at least 2 Invaders. Then, each Invader takes 1 Damage per Strife it has.",
            "Each player adds 1 Strife in a different land with at least 2 Invaders. Then, each Invader with Strife deals Damage to other Invaders in its land."),
        new FearCard(FearType.Expansion, "Dahan Threaten",
            "Each player adds 1 Strife in a land with Dahan.",
            "Each player adds 1 Strife in a land with Dahan. For the rest of the turn, Invaders have -1 Health per Strife to a minimum of 1.",
            "Each player adds 1 Strife in a land with Dahan. In every land with Strife, 1 Damage per Dahan."),

        // Events
        // Branchclaw
        new ChoiceEventCard("Years of Little Rain", "A terrible drought patches the island. You may:",
            [Events.LetThePlantsDieAndTheLandWither, Events.ActToEaseTheDrought],
            TokenEvent.BeastsAttack, DahanEvent.CannyDefense),
        new ChoiceEventCard("Farmers Seek the Dahan for Aid", "The Dahan are uncertain whether to teach the Invaders farming techniques more in tune with the island's life. You recommend they:",
            [Events.SpurnTheInvaders, Events.TeachTheInvaders],
            TokenEvent.NewDiseases, null),
        new ChoiceEventCard("New Species Spread", "New plants and animals brought by the Invaders damage the local ecology. You may:",
            [Events.LetTheInvasiveSpeciesBloom, Events.TransmuteTheWorstOfTheSpecies],
            TokenEvent.NewDiseases, DahanEvent.OfferingsOfPatternAndDance),
        new ChoiceEventCard("War Touches the Island's Shores", "Invaders from a different faraway land assault the ones here, torching farms and bombarding Cities. You may:",
            [Events.AllowTheAttacks, Events.HelpRepelTheNewcomers],
            TokenEvent.BeastsFindNewHomes, DahanEvent.ReclaimTerritory),
        new ChoiceEventCard("Sacred Sites under Threat", "Invaders have begun to find hidden places of natural power. You may:",
            [Events.LetTheIslandsStrengthRepulseThem, Events.GuardThemYourselfForWellOrIll],
            TokenEvent.BeastsProwl, DahanEvent.SpiritSpeakersSolveRiddlesOfPower),
        new ChoiceEventCard("Outpaced", "Humanity has always been faster than you, but the Invaders' terrifying speed catches you off-guard. Each Spirit chooses indepently for each of their Slow Power Cards played this turn:",
            [Events.StaySteadyAndSlow, Events.WorkToMatchTheirPace],
            TokenEvent.LingeringPlagues, DahanEvent.RaidsInForce),
        new ChoiceEventCard("Missionaries Arrive", "They teach and spread lessons of a foreign god. You may:",
            [Events.IgnoreTheirContactWithTheDahan, Events.CurseTheTonguesOfTheForeigners],
            TokenEvent.PreyOnTheUnwary, null),
        new ChoiceEventCard("A Strange Madness among the Beasts", "They grow even wilder and more savage. You may:",
            [Events.LetThemRampageUntoDeath, Events.GuideTheMadness],
            TokenEvent.SavageFrenzy, DahanEvent.SeekASaferHome),
        new StageEventCard(Events.SeekingTheInterior, Events.LocalDiaspora, Events.LocalDiaspora,
            TokenEvent.BeastsProwl, DahanEvent.ForsakeTheBarrenLand),
        new StageEventCard(Events.WaveOfReconnaissance, Events.Urbanization, Events.Urbanization,
            TokenEvent.Stricken, DahanEvent.Retreat),
        new StageEventCard(Events.InterestingDiscoveries, Events.IncreasingAggression, Events.IncreasingAggression,
            TokenEvent.WheezelungOutbreak, DahanEvent.TendTheLand),
        new StageEventCard(Events.StrangeTalesAttractExplorers, Events.Fortification, Events.Fortification,
            TokenEvent.BeastsAttack, DahanEvent.ComingOfAge),
        new TerrorLevelEventCard(Events.CulturalAssimilation, Events.CulturalAssimilation, Events.ReprisalAgainstTheDahan,
            TokenEvent.BeastsAttack, DahanEvent.RecklessOffensive),
        new TerrorLevelEventCard(Events.InvestigationOfDangers, Events.DestroyTheUnnatural, Events.DestroyTheUnnatural,
            TokenEvent.PreyOnTheUnwary, DahanEvent.RouseTheSpirits),
        new TerrorLevelEventCard(Events.DistantExploration, Events.FearfulMobs, Events.FearfulMobs,
            TokenEvent.GrimToll, DahanEvent.FierceMein),
        new ChoiceEventCard("Rising Interest in the Island", "Your island is unlike any the Invaders have seen. Their leaders begin to take interest in tales of strangeness. You may:",
            [Events.IgnoreTheCuriosity, Events.WeaveLiesInTheMindsOfTheirObservers],
            TokenEvent.BeastsOfTheJungle, DahanEvent.TrapsAndSnares),
        new HealthyBlightedLandEventCard(Events.PuttingDownRoots, Events.TheCenterCrumbles,
            TokenEvent.Stricken, DahanEvent.DriveOffTheInterlopers),
        new HealthyBlightedLandEventCard(Events.SearchForNewLands, Events.DevastatedShores,
            TokenEvent.DistantHunt, DahanEvent.CannyDefense),
        new HealthyBlightedLandEventCard(Events.InvadersSurgeInland, Events.WideningDestruction,
            TokenEvent.GrimToll, DahanEvent.CannyDefense),
        new HealthyBlightedLandEventCard(Events.TightKnitCommunities, Events.BlightSpreads,
            TokenEvent.PreyOnTheUnwary, DahanEvent.ComingOfAge),
        new HealthyBlightedLandEventCard(Events.WellPreparedExplorers, Events.BlightSpreads,
            TokenEvent.BeastsProwl, DahanEvent.ComingOfAge),
        new HealthyBlightedLandEventCard(Events.PopulationRises, Events.PowerFades,
            TokenEvent.SandfeverOutbreak, DahanEvent.OfferingsOfPatternAndDance),
        new HealthyBlightedLandEventCard(Events.UrbanDevelopment, Events.FesteringPitsOfBlight,
            TokenEvent.LingeringPlagues, DahanEvent.FierceMein),
        new HealthyBlightedLandEventCard(Events.HeavyFarming, Events.OvercrowdedCities,
            TokenEvent.PreyOnTheUnwary, DahanEvent.ComingOfAge),
        new HealthyBlightedLandEventCard(Events.PromisingFarmland, Events.NewCashCropsTakeHold,
            TokenEvent.BeastsProvoked, DahanEvent.CannyDefense),
        new AdversaryEvent("Slave Rebellion", Adversary.KingdomOfFrance,
            new StageEventCard(Events.SmallUprising, Events.SmallUprising, Events.Rebellion,
                null, DahanEvent.AidTheUprising)),
    ];
}
